### PR TITLE
Add PlanetScale

### PR DESCRIPTION
**Pull request by nhlong2**
PlanetScale is a MySQL compatible, serverless database platform powered by Vitess, 3 databases for free with 10GB storage, 100 Million rows read/mo per database, and 10 Million rows written/mo per database.
[Pricing](https://planetscale.com/pricing)

### CODE REVIEW

**Comment by ripienaar** [comment]
Looks neat but what does the "BETA" tag mean there on the pricing page, will this offer vanish post beta?

**Comment by nhlong2** [comment]
> Looks neat but what does the "BETA" tag mean there on the pricing page, will this offer vanish post beta?

No, they try to keep it free forever.
[Proof](https://twitter.com/thierylaverdure/status/1394734870115586050#m)

**Comment by ripienaar** [comment]
amazing, definitely one I will be trying myself!

**Comment by ripienaar** [comment]
thank you

**Pull request merged**
