### PR TITLE
Adding Tally.so Update README.md

### PR DESCRIPTION
**Pull request by henri470**
### New Submission Check List

Please ensure your submission ticks all of these boxes:

 - [x] This is Software as a Service not self hosted
 - [x] It has a free tier not just a free trial
 - [x] The submission mentions what is free
 - [x] The submission is not already present in the list
 - [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by henri470** [comment]
hi there, sorry in advance, i really wanted to contribute to this amazing project that helps me so much, but i really dont know how to do pull request (my very first pull request), i hope i got this right, pardon me.

**Comment by FatGrizzly** [comment]
Hi. your PR is well and good, kindly change the description of service, it needs to be something like what the service offers and what is free

**Comment by henri470** [comment]
Hi, i updated the description of service. I hope i did it the right way. Thank you

**Comment by FatGrizzly** [comment]
All good buddy 👍

Thank you for your contribution

**Pull request merged**
