### PR TITLE
Add devmind.io

### PR DESCRIPTION
**Pull request by LukasMeine**

### CODE REVIEW

**Comment by ripienaar** [comment]
I can't verify this is true unfortunately, the pricing link seems to be https://devmind.io/planos but this just redirect backs to / where this is not stated

```
% curl -v -X HEAD https://devmind.io/planos
#.....
> HEAD /planos HTTP/1.1
> User-Agent: curl/7.29.0
> Host: devmind.io
> Accept: */*
>
< HTTP/1.1 302 Found
#....
< Location: https://devmind.io
```

**Comment by LukasMeine** [comment]
Thank you very much for the feedback! It was an intentional behavior. We did that to redirect the user to the index page, where he would see a modal explaining that devmind is free to use. But we just talked among ourselves and decided to bring back our pricing page. Hope you can verify it now :)

**Comment by ripienaar** [comment]
@LukasMeine how long is the free trial for, doesnt say?

**Comment by LukasMeine** [comment]
We are actually validating the product, so we will keep it free for a while. No plans to begin charging for now.

**Comment by ripienaar** [comment]
Then I am afraid I can't add it, from the top of the document:

```
NOTE: This list is only for as-a-Service offerings, not for self-hosted software. For a service to be eligible it has to offer a Free Tier and not just a free trial. If the Free Tier is time bucketed it has to be at least a year.
```

I need to be able to verify this is true for a new service.  Yes companies sometimes dont last that long, but the intention should be clear

**Comment by LukasMeine** [comment]
Got it. But there is indeed a free tier that will last long. We will keep it for open source projects for ever, the price validation is only for the private projects :)

**Comment by ripienaar** [comment]
Sounds great. Maybe I missed it but if the pricing page could clarify they we are good to go

**Comment by ripienaar** [comment]
I see no such thing

**Comment by JABirchall** [comment]
on the bottom of the home page says 1 week.
1 week
But honistly that is not free for dev, its just a _short_ trial.

**Comment by LukasMeine** [comment]
hmm... That's a problem with our translation files. Just checked that our text is correct ( with the free plans ) in portuguese, but our translators forgot to add that to the english translation. thanks for the tip, we are changing that right now!

**Comment by LukasMeine** [comment]
image
As you can see, the text in portuguese was correct, but the english translation was wrong. I totally missed that. Sorry about it, Our translators are working at it right now.

**Comment by LukasMeine** [comment]
Just wanted to tell you guys that while we were fixing the pricing page, we also found some more outdated english content in other pages as well. Thank you very much for helping us to find that! @JABirchall and @ripienaar I owe you guys a beer 🍺

And I will let you know once we update all the english content so you can check it out again. Again, thank you very much.

**Comment by ripienaar** [comment]
closing this one, no update for ages, feel free to reopen if still relevant

**Pull request closed without merging**
