### PR TITLE
Remove EVA (eva.pingutil.com)

### PR DESCRIPTION
**Pull request by ItsNiceCraft**
Removed EVA (eva.pingutil.com) because it has been down for several months now. pingutil.com is also down.

### CODE REVIEW

**Comment by ripienaar** [comment]
thank you

**Comment by FatGrizzly** [comment]
@ripienaar the api still seems to work from my end, with an invalid cert

**Comment by ripienaar** [comment]
hmm, now that I look again (I checked only pingutil.com) I see eva is up for me. but with the main site down, its just a below par service so inlined to remove it

**Comment by ItsNiceCraft** [comment]
Weird, it's up again! Altough I checked a few months ago and it was down as well, then, an hour ago I checked again and submitted this pr

**Pull request merged**
