### PR TITLE
Added ACRA

### PR DESCRIPTION
**Pull request by balzathor**
Added [ACRA](http://acra.ch) In-App Crash Reporting to Crash / Exception Handling

### CODE REVIEW

**Comment by ripienaar** [comment]
I've had a few PR for similar free and non-free ones and didnt accept them because they are purely mobile orientated.

The list is intended to be services of use to infrastructure devs/devops types so this kind of tool would be useful if it had a wider scope but as a pure android mobile app targetted tool I am not sure it fits the bill

**Comment by balzathor** [comment]
Well but this one sure does help a lot in terms of handling log files and keeping the Dev updated about the bugs that the application has. With this, it becomes a lot easier to splat bugs as log report is sent to the dev as soon as the application crashes. Probably a must have for all devs who have lengthy codes.

**Comment by ripienaar** [comment]
I am not saying it isn't useful, I am saying it doesnt seem to fit the focus of this list.

**Comment by balzathor** [comment]
Alright, I'll come up when I find something more interesting.

Regards.

**Comment by ripienaar** [comment]
thanks, sorry for being a pain, do appreciate the effort :)

**Comment by balzathor** [comment]
Sure, it's all good :)

**Pull request closed without merging**
