### PR TITLE
Remove Okteto Cloud

### PR DESCRIPTION
**Pull request by pchico83**
Due to mining abuse, we are removing our free tier soon :-(

### CODE REVIEW

**Comment by Robokishan** [comment]
very sad i just found out this repo from news letter and saw this commit. i was about to give a shot

**Comment by ripienaar** [comment]
Crypto ruins everything.

**Comment by FatGrizzly** [comment]
> Crypto ruins everything.

Yes :|

**Comment by GaMoCh** [comment]
> Due to mining abuse, we are removing our free tier soon :-(

Cryptomining ruins everything.

Are you thinking of taking some action in the future like GitLab did? [How to prevent crypto mining abuse on GitLab.com SaaS](https://about.gitlab.com/blog/2021/05/17/prevent-crypto-mining-abuse/), or adopt solutions like CircleCI? [How we find, block, and prevent cryptomining at CircleCI](https://circleci.com/blog/how-we-find-block-and-prevent-cryptomining-at-circleci/).

Okteto is an excellent platform, congratulations for the excellent work! I hope that in the future the free plan will come back.

**Comment by futchitwo** [comment]
Looks like there is still a free developer tier?
https://okteto.com/pricing/

**Comment by ripienaar** [comment]
Thanks @futchitwo I reverted this removal

**Pull request merged**
