### PR TITLE
www2png.com seems dead

### PR DESCRIPTION
**Pull request by berdav**
Hi, www2png.com seems unreachable.

It return 504 upon a request.

### CODE REVIEW

**Comment by ripienaar** [comment]
thank you :)

**Comment by LoYungSum** [comment]
It seems that it's back online now

**Comment by ripienaar** [comment]
still dead to me

**Comment by berdav** [comment]
Yeah, it is switching between timeout and working.

I contacted the webmaster and he said that the site is having overloading problems and he wants to move it to a more powerful server.

**Pull request merged**
