### PR TITLE
pp.ua free domain

### PR DESCRIPTION
**Pull request by kouhe3**
free domain - pp.ua

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks

**Comment by ICTman1076** [comment]
Tried this service, appears to want card details. Perhaps worth noting?

**Comment by ripienaar** [comment]
Many services require card details for free services, it prevents abuse and keeps the service safe.  Did you try it?

**Comment by ICTman1076** [comment]
I did not register the domain in the end because I was uncomfortable with giving my card details, especially since it is a subdomain of pp.ua and not a FQDN.

**Pull request merged**
