### PR TITLE
Add `nudge-hook.net`

### PR DESCRIPTION
**Pull request by jimpil**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

Note that this is a completely free & unlimited api (at least with respect to how many schedules one can create). As such, there is no signup required, no login screen, or api-key etc. In other words, the only piece of user-related info the server needs to know is simply an email address (of the job-owner) - no card details, or login credentials are stored anywhere!

### CODE REVIEW

**Comment by jimpil** [comment]
By the way, the entry for `posthook.io` is outdated. There is no loger a free tier - it starts at $19. I'm not sure how you want to handle this though, as it no longer qualifies for this list.

**Comment by ripienaar** [comment]
You can update yours to just remove it or send a new one.

**Comment by jimpil** [comment]
Done

**Comment by ripienaar** [comment]
thank you

**Pull request merged**
