### PR TITLE
Moved Opbeat to Monitoring list.

### PR DESCRIPTION
**Pull request by makwarth**
Since the monitoring list is getting quite long, it might be helpful to split it into multiple lists, like "server monitoring", "application monitoring", "alerting" .. Happy to help :)

### CODE REVIEW

**Comment by ripienaar** [comment]
yeah its a pain, I am hoping to get some time to develop a website where entries can have multiple tags or catagories which will help.

Will move this one for now, but yeah def need something better and I think no matter what we do this one-giant-readme just wont get any better :P

**Comment by makwarth** [comment]
I actually like the simplicity of the giant readme - and the fact that it's on github. Let me know if you want help tidying up the lists :)

**Comment by cheiff** [comment]
Hi,

maybe this project can help:
https://github.com/mwozniak/bookmark-manager

Regards

**Comment by ripienaar** [comment]
Indeed the fact that it's just some file is I believe one of the main keys to success - its easy for anyone to quickly edit/add an entry even in the github editor

So the site I've been hacking on now and then has a very similar - but slightly more structured - flat file as  "database" to hopefully keep the easy workflow for contributors while giving higher order structure and functionality.

@makwarth help would be good, if you have a proposal it would be nice to see it outlined - just write a comment detailing it rather than do a ton of work on editing the doc and making a PR. 

Once we have an idea of where we're headed we can do work?

@cheiff thanks - but as above, I want to avoid DBs

**Comment by cheiff** [comment]
Yes, I understand. I also like the flatfile solution.

If you want to work on a flat file solution with tags, etc, I'll be 
happy to help.

**Comment by paulbrab** [comment]
What about storing it in json?

**Comment by ripienaar** [comment]
@paulbrab JSON isnt very human friendly, if it has to come to a serialized format it'll probably have to be YAML or TOML I suppose

**Comment by Waterloo** [comment]
Can't we scrap the list

**Comment by paulbrab** [comment]
apologies @ripienaar I meant for use in a website instead of a db, but yes, not very friendly for editing

**Comment by makwarth** [comment]
@ripienaar Been giving this some thought and I honestly think the list is working as it is. Over time, large lists should be split into sub-lists, but for now I would just make sure all entries have a concise description of the product offering. [name] - [what it does in] - [free plan conditions]

**Comment by ripienaar** [comment]
@makwarth yeah, I do intend to keep it almost that simple with just a few extra fields, so you end up with a human readable README that's effectively a serialised data structure to drive a web view of same.

Thus keeping the easy to edit and search with ^F etc nature and adding the ability to present the categories better and add entries into multiple categories - this has been a very common thing in PRs, the same service in multiple categories and it will make this list massive and impossible to manage if we did it via duplication

**Comment by makwarth** [comment]
@ripienaar cool :+1:

**Comment by TraderStf** [comment]
I have suggest this tools long time ago.
https://github.com/ripienaar/free-for-dev/issues/111

**Comment by ripienaar** [comment]
Thanks @TraderStf but as you can see from the preceding discussion ones with Databases will not work

**Pull request merged**
