### PR TITLE
Add LabEx to list of Education and Career Development

### PR DESCRIPTION
**Pull request by huhuhang**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by huhuhang** [comment]
Hi, maintainers

LabEx, founded in 2017, specializes in practical instruction for Linux and DevOps. We believe hands-on learning is the most effective way to master programming, which is why we offer an online practice environment that enables users to learn through direct experience.

LabEx offers extensive free content (Include LabEx Teams) for university teachers to use in their classrooms at no cost. Additionally, we provide extra resources for developing countries, reinforcing our commitment to equitable education.

Thank you for your review. 😄

**Comment by ripienaar** [comment]
I dont think this is suitable for this list, the teams feature seems like a way to manage learning on this platform only? That's not broad enough for this list

**Comment by huhuhang** [comment]
@ripienaar, thank you for your reply. I understand your concerns. 

So, is LabEx suitable to be added to "Education and Career Development" section?

1. We provide thousands of manually reviewed tutorials on Linux, DevOps, and Coding that can be accessed without registration: https://labex.io/tutorials
2. We offer free users a daily quota of 3 hours of virtual environment usage.

Looking forward to your response. If possible, I will update the PR. 😄

**Comment by ripienaar** [comment]
labex itself would qualify yes

**Comment by huhuhang** [comment]
@ripienaar Thank you for your reply. I have updated the PR and moved LabEx to the "Education and Career Development" section. 😄

**Comment by ripienaar** [comment]
Thanks

**Pull request merged**
