### PR TITLE
Split out DNS into its own section

### PR DESCRIPTION
**Pull request by dandart**
Web hosting was a mix of web hosting and DNS - so this splits them apart

### CODE REVIEW

**Comment by ripienaar** [comment]
nice, thanks

**Comment by tomick** [comment]
@ripienaar Maybe move Cloudflare to DNS section?

**Comment by dandart** [comment]
good point - it counts too

**Comment by ripienaar** [comment]
I think they are a CDN first and the DNS stuff is a side feature. Not sure I am keen on listing the same thing many times - but then in their primary use first

**Comment by dandart** [comment]
Oops - I duplicated above not realising that wasn't your intention - I'd personally have everything that does dns under dns etc, just for ease of search

**Comment by ripienaar** [comment]
In the mid term I am going to write some web app for this data that has something like tags or a entry in different categories or such

This once I am done moving countries. Till then I am a bit weary of exploding the size of this rather inefficient current format

**Pull request merged**
