### PR TITLE
Add brothers

### PR DESCRIPTION
**Pull request by tvvocold**
:)

### CODE REVIEW

**Comment by ripienaar** [comment]
hmm, make something called "Other Lists" and put it down the bottom and add it to the TOC, that'll be less distracting from the purpose of the list :)

**Comment by tvvocold** [comment]
Feel free to close this PR or put it down the bottom.
But we will stay (put  brothers (like free-for-dev or whatever-for-dev) in the head :)

**Comment by ripienaar** [comment]
well if you updated this PR as described I'd be happy to merge it

**Comment by tvvocold** [comment]
Done

**Comment by ripienaar** [comment]
thanks, I am going to make a website for this and will then move links to other lists to some more prominent place

**Comment by tvvocold** [comment]
Thx too.
Use [Github Pages](https://pages.github.com/) is a good choice for this sort of thing i think.

**Pull request merged**
