### PR TITLE
Revert rename of README.MD

### PR DESCRIPTION
**Pull request by marcjamot**
In the PR https://github.com/ripienaar/free-for-dev/pull/1685/files, `README.md` was renamed to `patch-1` breaking https://free-for.dev/#/. This is a revert of that name change.

### CODE REVIEW

**Comment by marcjamot** [comment]
@ripienaar ping just in case :D

**Review by oscarsilver — APPROVED** [review]

**Comment by ripienaar** [comment]
ah, yikes, thanks for that!

**Comment by SKGHD** [comment]
As of making this comments the site is still broken though.

**Comment by ripienaar** [comment]
It's fine now - i suspect there might be some caches and stuff involved :)

**Pull request merged**
