### PR TITLE
Add in NATS and NGS

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

### CODE REVIEW

**Comment by ripienaar** [comment]
yay, though, I am not that keen on single entry sections, either stick it in `STUN, WebRTC, Web Socket Servers and Other Routers` or pull the rabbitmq and one or 2 other pure pub sub stuff there into this catagory?

**Comment by derekcollison** [comment]
I can pull them over to new category. You do sort by name yes?

**Comment by ripienaar** [comment]
I dont sort now, but I probably will soon so you might as well sort it :)

**Comment by derekcollison** [comment]
ok will do.

**Comment by derekcollison** [comment]
ok pushed update.

**Comment by ripienaar** [comment]
thank you!

**Pull request merged**
