### PR TITLE
add awesome_bot config and some cleanups

### PR DESCRIPTION
**Pull request by ripienaar**

### CODE REVIEW

**Comment by dkhamsing** [comment]
@ripienaar hey so looks like kanbanpad should be removed

http://www.kanbanpad.com/

kanbanpad

**Comment by dkhamsing** [comment]
I can make it work with 

```
--allow-redirect --white-list github.com,hub.jazz,yandex.com/domains_add,debugmail
```

but yeah let me think of the other issue you created

**Comment by ripienaar** [comment]
Thank you @dkhamsing

**Comment by dkhamsing** [comment]
:smile:

**Pull request merged**
