### PR TITLE
Add domcloud.co to list of free PaaS services

### PR DESCRIPTION
**Pull request by willnode**
### New Submission Check List

Please ensure your submission ticks all of these boxes:

 - [X] This is Software as a Service not self hosted
 - [X] It has a free tier not just a free trial
 - [X] The submission mentions what is free
 - [X] The submission is not already present in the list

### CODE REVIEW

**Comment by willnode** [comment]
Oh, I see `Web Hosting` category too. What's the difference? Should I move it there too?

**Comment by ripienaar** [comment]
We list each entry once only so if you want to move it go ahead else we can merge as is

**Comment by willnode** [comment]
I think it gonna be closer to PaaS sooner or later so I think we're good to merge as is 👍

**Comment by ripienaar** [comment]
Thank you

**Pull request merged**
