### PR TITLE
Added Dream Factory

### PR DESCRIPTION
**Pull request by paulocarvalhodesign**
Added the cool software Dream Factory.

### CODE REVIEW

**Comment by ripienaar** [comment]
do they have a hosted service with a free tier? This list is for *aaS software with free tiers.

**Comment by paulocarvalhodesign** [comment]
yeah they have a free cloud version where you and start and eventually you can export and migrate .

**Comment by paulocarvalhodesign** [comment]
https://www.dreamfactory.com/user/register

**Comment by ripienaar** [comment]
great, thanks

**Pull request merged**
