### PR TITLE
Added Bitdefender and Obsidian to the "Other Free Resources" section

### PR DESCRIPTION
**Pull request by sudeepbm**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
While these are great this list is for SaaS with a few minor exceptions like IDEs 

you clicked that these are SaaS services please expand on what they offer free as a SaaS

**Comment by sudeepbm** [comment]
Bitdefender offers several free Software as a Service (SaaS) security solutions, including:

1. Bitdefender Antivirus Free Edition: This provides essential antivirus protection for your computer, scanning and removing malware, without any cost.
2. Bitdefender Virus Scanner for Mac: A free antivirus solution specifically designed for Mac users, offering real-time protection against malware.
3. Bitdefender Online Threat Prevention: This is a free browser extension that blocks malicious web pages, phishing attempts, online trackers, and annoying ads. It also warns users about unsafe links in social media and email messages. It works with Chrome, Firefox, Edge, and Safari browsers.

Also sorry for giving some wrong information. Obsidian is not a SaaS. Rather it stores your notes locally as plain text files.

Hope this answers your question. If this answer meets your requirements, I wish you will merge my pull request or suggest any changes.
Thanks in advance🤗.

**Comment by ripienaar** [comment]
The software you install is installed locally and run on your machine. 

Sure they probably get databases and updates etc from a service. 

But I think I will rather pass on these predominantly local pieces of software.

**Comment by sudeepbm** [comment]
I appreciate your perspective, and I'm open to relying on your opinion.

**Pull request closed without merging**
