### PR TITLE
Added revolt.chat

### PR DESCRIPTION
**Pull request by Yu14Y**
Added revolt.chat
an all in one alternative for discord 

## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by Yu14Y** [comment]
Screenshots : 


appearance06
chatting
main home page

**Comment by Tr0llie** [comment]
> Added revolt.chat an all in one alternative for discord

It is not fully polished as discord but can be a great alternative for discord
i can vouch that as a revolt user as discord is ran by a big company while revolt is community ran and isn't really polished. there seems to be bugs here and there but overall works fine.

**Comment by Yu14Y** [comment]
> It is not fully polished as discord but can be a great alternative for discord 

atleast it doesn't use much system resource as discord. 

> while revolt is community ran and isn't really polished.

With their latest patch, seems as tho it is almost as polished as discord. 

> bugs here and there but overall works fine.

Just like discord, but the community is trying is best to fix most of the bugs. + a bonus point for an active support community

**Comment by ripienaar** [comment]
thanks

**Comment by Yu14Y** [comment]
> thanks

welcome

**Pull request merged**
