### PR TITLE
Added a "For Students" section

### PR DESCRIPTION
**Pull request by AnthonyBobsin**
The "For Students" section contains any free software available exclusively for students.

### CODE REVIEW

**Comment by ripienaar** [comment]
hmm, not sure how I feel about this, its handy but its not categorised, let me think for a bit :)

**Comment by AnthonyBobsin** [comment]
If you like I could set up some categories as well. Majority of them are packages of different software, that's the only thing. Sounds good though, let me know :)

**Comment by ripienaar** [comment]
yeah there's already a 'other collections' list, might go in there.

the end goal is to make a site dedicated to this data, and for all the others that are free for open source I'd add some icon or badge or something and sort the categories so they are listed first before the rest.

I imagine I could do something similar with these in the 'other bundles' section, but not sure - I am mid moving home so not got time to get my thoughts in gear.

Maybe move them to the other section and just say someting like each being free for students and then when I process this list into the website I'll give them the same treatment as I would the open source ones - some kind of badge or emojii next to them

**Comment by AnthonyBobsin** [comment]
That makes sense, this list is amazing but it is getting pretty large. I was also thinking that for now at the bottom of each the appropriate category, I could add a students subsection and place these websites accordingly.

Additionally, since you are interested in implementing a website, I currently run a website called techether where users add various learning material for programming languages and frameworks. It's all open source right now and you can view it all on my Github page. If you are interested, I think we would be able to merge both our information together somehow, since there are many similarities between our communities. Here's a link to the website so far http://techether.com/ . If you aren't interested in doing a merge, I would still love to help out with your website as well.

**Comment by ripienaar** [comment]
Thanks for the offer. Let me get this house move shit out of the way and I can think clearly. Next week sometime I will come back to this one of you don't mind. 

Honestly I expected to get 40 or 50 links max. It's been pretty mind blowing. The site I made early on is not going to cut it so I am rethinking the UX I had in mind. Crazy days. 

---
R.I.Pienaar

**Comment by AnthonyBobsin** [comment]
Sounds great, I look forward to hearing back from you.
Good luck with the moving!

**Comment by najela** [comment]
Hey @ripienaar @AnthonyBobsin  I created a list of discounts for student devs here https://github.com/najela/discount-for-student-dev. This PR will be welcomed there ):

**Comment by nurazhar** [comment]
you mean like https://education.github.com/pack ?

**Pull request closed without merging**
