### PR TITLE
Removed tebi.io from  IaaS

### PR DESCRIPTION
**Pull request by nextpier**
### Free SaaS Offering Submission

Thank you for contributing to this list. This list is for **SaaS**
services that offer a **free tier** to help developers evaluate and
build something that users can later use and get support for.

The focus of this list is quite broad but we try to keep things
limited to that which infrastructure developers, like DevOps Practitioners,
would find useful.

We do not anymore accept cPanel like PHP+MySQL hosting services.

### New Submission Check List

Please ensure your submission ticks all of these boxes:

 - [ ] This is Software as a Service not self hosted
 - [ ] It has a free tier not just a free trial
 - [ ] The submission mentions what is free
 - [ ] The submission is not already present in the list

### Thank You

This list is the result of more than a thousand people contributing
to make something useful, we appreciate your efforts.

---   
---  
tebi.io has now  a free tier + pay-as-you-go as basic option. It expires in 14 days.  After that period data becomes read-only, and requires card (no prepaid accepted)  to go on.  I think it should be removed from this list.

[https://tebi.io/#faq](https://tebi.io/#faq)  

tebi io-1

### CODE REVIEW

**Comment by rachit1601** [comment]
But the free teir still hai 25GB storage and 250gb transfer

**Comment by rachit1601** [comment]
https://tebi.io/#prices

**Comment by ripienaar** [comment]
```In the Free Tier you have 25 GB of storage (with 2 copies) and 250 GB of traffic. This volume of services is credited every month for free. If you are using more storage or bandwidth, you just need to pay for the amount that exceeds the Free Tier.
```

Still seems legit to me and being that you pay for overages seems fine to ask for CC, other services do this too.

**Comment by nextpier** [comment]
Ok :-)
Maybe just mention the mandatory card

**Pull request closed without merging**
