### PR TITLE
add yourquerys.ml

### PR DESCRIPTION
**Pull request by suryapratapsinghsuryavanshi**
add `yourquerys.ml` to the other open developer resources, it is a SPA application for sending feedback directly to your email without any database integration, with cross-platform functionality.

### New Submission Check List

Please ensure your submission ticks all of these boxes:

 - [x] This is Software as a Service not self hosted
 - [x] It has a free tier not just a free trial
 - [x] The submission mentions what is free
 - [x] The submission is not already present in the list
 - [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
There doesnt seem to be contact details or a privacy policy on this offering

**Comment by suryapratapsinghsuryavanshi** [comment]
> There doesn't seem to be contact details or a privacy policy on this offering

This is an initially open-source project later I will try to be fully transparent with the privacy policy.

**Comment by ripienaar** [comment]
Well I assume you read the tick boxes you ticked, right?

**Comment by FatGrizzly** [comment]
I don't really think this is useful for the list, considering its on a free domain, that too freenom. Which is complete bs since it randomly steals your domain.

**Comment by suryapratapsinghsuryavanshi** [comment]
> I don't really think this is useful for the list, considering its on a free domain, that too freenom. Which is complete bs since it randomly steals your domain.

Okay, so suggest to me what is the right place for this application.

**Comment by suryapratapsinghsuryavanshi** [comment]
> Well I assume you read the tick boxes you ticked, right?

No problem within some time I will fix all the issues, please wait.

**Comment by FatGrizzly** [comment]
> Okay, so suggest to me what is the right place for this application.

I don't know. Your service runs on a free domain, doesn't have a ToS nor a privacy policy, no contact details, doesn't force SSL on a HTTP request.

**Pull request closed without merging**
