### PR TITLE
Add Darklang

### PR DESCRIPTION
**Pull request by pbiggar**
Darklang is a pretty wide product and fits in a lot of the categories, so I tried to keep it in just the major categories where you would go looking for something like Dark: BaaS, PaaS and Editor.

### CODE REVIEW

**Comment by ripienaar** [comment]
Thanks. We try to list things in one category only - the list is a bit wild already 

further I don’t see details about what, or even if, they wil offer a free tier post their betas which is a requirement for being on the list. 

Could have missed it though feel free to stock a link here with details

**Comment by pbiggar** [comment]
Thanks for the reply.

> Thanks. We try to list things in one category only - the list is a bit wild already

OK, sounds good. It probably makes sense to stay in the BaaS category so I'll make that change.

> further I don’t see details about what, or even if, they wil offer a free tier post their betas which is a requirement for being on the list.

Yes, we haven't actually figured out what we'll offer or even what unit we'll offer in. Would something like "free during the beta, generous free tier planned after beta" work for you?

**Comment by ripienaar** [comment]
Yes that would work - see top of the readme that’s about the level of rigor I apply, just want to know a free tier is planned

**Comment by pbiggar** [comment]
> Yes that would work - see top of the readme that’s about the level of rigor I apply, just want to know a free tier is planned

Great, I've updated the PR. Thanks!

**Comment by ripienaar** [comment]
Ah, well sorry I was not clear, I need to be able to see this stated on the website of the service in question, not in the comment here - sure keep it here of course, but I have to be able to verify the offer and also those who later update entries.

So if there's a place on the https://darklang.com/ site that says its planned great, else I just don't know.

Sorry for not being clearer earlier, I know updating this is a pain

**Comment by pbiggar** [comment]
Gotcha! How's this? https://darklang.com/language#faq-pricing

**Comment by ripienaar** [comment]
winner

**Comment by ripienaar** [comment]
thank you  :)

**Comment by pbiggar** [comment]
Awesome, thanks!

**Pull request merged**
