### PR TITLE
fix(readme): fix table of contents link to ci/cd

### PR DESCRIPTION
**Pull request by papb**

### CODE REVIEW

**Comment by ripienaar** [comment]
we've now had like 5 PRs "fixing" this - turns out the free-for.dev site and the github readme have competing patterns and we can only fix it for one a time.

So lets see about fixing this for both, please adjust the heading for CI/CD like this:

```
### <a name="cicd"></a>CI / CD
```

And then update the link to `#cicd`

**Comment by papb** [comment]
Oh! Will do

**Comment by papb** [comment]
@ripienaar Done, thanks

**Comment by ripienaar** [comment]
thank you :)

**Comment by ripienaar** [comment]
Lol and still its not fixed, i think I will just rename the section to `CI and CD` lol, the `/` confuses things

**Comment by papb** [comment]
:thinking: oh well

**Pull request merged**
