### PR TITLE
getawesomeness

### PR DESCRIPTION
**Pull request by TraderStf**

### CODE REVIEW

**Comment by ripienaar** [comment]
this is nice, but maybe put it down the bottom by "other lists"?

**Comment by TraderStf** [comment]
don't understand, can do it it's ok for me...

**Comment by ripienaar** [comment]
I mean there is a section called "Other Lists" just put it down there in this document

**Comment by TraderStf** [comment]
??? that's where I put it??

Other lists

https://github.com/httpsGithubParty/FOSS-for-Dev - A hub of Free and open-source software for developers
https://github.com/pborreli/free-for-nonprofit - List of free services for non-profit organisations
https://www.fullcontact.com/developer/pricing/ - Help your users know more about their contacts by adding social profile into your app. 500 free Person API matches per month.
>>>>>http://getawesomeness.com/ - retrieve all amazing awesomeness from Github... a must see!

**Comment by ripienaar** [comment]
ah wth, i must be blind, sorry about that :)

**Pull request merged**
