### PR TITLE
Adding houndify.com

### PR DESCRIPTION
**Pull request by bengadbois**

### CODE REVIEW

**Comment by bengadbois** [comment]
The CI failures are due to other changes existing in master, not from this PR

**Comment by ripienaar** [comment]
where do you see the details of their free tier? I do not see a pricing page anywhere which makes it hard to verify

**Comment by TraderStf** [comment]
https://www.houndify.com/contact
here talk about pricing question, no mention of free for dev
and their conditions dooo, 'become a slave'

**Comment by bengadbois** [comment]
You have to register for an account to view the pricing info.

http://i.imgur.com/Kgm8txE.png

**Comment by ripienaar** [comment]
OK, that's unfortunate, for me it's important to be able to verify the validity of the entries on the list - a tool that expects me to sign up isn't realistic.

I've had a few of these kind of scenarios and rejected them all, so unfortunately I'll have to do the same here.

Sorry and thank you for the effort in creating the PR I really appreciate it.

**Pull request closed without merging**
