### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manthankool**
Added another FREE API for scraping.

### CODE REVIEW

**Comment by ripienaar** [comment]
I reverted this PR, I dont think this is a free tier service.

**Comment by manthankool** [comment]
This is a free service upto 1000 free credits.

**Comment by ripienaar** [comment]
I see `Get started with 1000 calls for FREE per month` can you add that to the description initially I only saw 1000 credits, not that it's ongoing and every month.

**Comment by manthankool** [comment]
O have added "free pack available"

**Pull request merged**
