### PR TITLE
Move RemoteMySQL service to DBaaS section

### PR DESCRIPTION
**Pull request by sdil**
It's more sensible in that section

### CODE REVIEW

**Comment by ripienaar** [comment]
please rebase against master looks like this one is against slightly older code

**Comment by sdil** [comment]
Fixed :)

**Comment by ripienaar** [comment]
OK - but now you left it in the old section :P

**Comment by sdil** [comment]
:man_facepalming:

**Comment by sdil** [comment]
Sorry for my clumsy mistakes.

**Comment by ripienaar** [comment]
thank you :)

**Pull request merged**
