### PR TITLE
add Strapi CMS

### PR DESCRIPTION
**Pull request by aryad14**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by iggy** [comment]
You should take out the formatting changes at least. I also don't see anything about what's free. The pricing page shows the cheapest plan is $29 per month.

**Comment by aryad14** [comment]
Hello. Thank you for the reply.
If you take a look at the Pricing Page clearly, you can see 2 categories: Self-Hosted and Cloud
There is a Free Tier available in the Self-Hosted Category. The $29 price you see is for using the Strapi Cloud service for hosting

### The Self-Hosted Category Pricing
image
 
### The Cloud Category Pricing
image

**Comment by ripienaar** [comment]
This is a list for SaaS with free tiers not self hosted

**Comment by aryad14** [comment]
Ok. Strapi is a good Headless CMS so thought it would be better to share.

**Pull request closed without merging**
