### PR TITLE
Format list

### PR DESCRIPTION
**Pull request by mikestreety**
Spacing updates, Alphabetize the lists and resolve the CI/CD link

### CODE REVIEW

**Comment by ripienaar** [comment]
how did you sort this list? It would be impossible for me to maintain the ordering going forward :)

**Comment by mikestreety** [comment]
In my IDE, I selected each section and sorted it.

Why would it be difficult to maintain? Now they are in an order - any PRs or other additions ca be slotted in

**Comment by ripienaar** [comment]
Because it’s a barrier I don’t want to raise for contributors

**Comment by mikestreety** [comment]
Fair enough. As a contributor (and maintainer), I would prefer it in alphabetical so I can avoid duplicates. As a user I struggled to scan the list - but that it just me!

**Pull request closed without merging**
