### PR TITLE
add gitcafe.com

### PR DESCRIPTION
**Pull request by akar1nchan**
add gitcafe.com

### CODE REVIEW

**Comment by ripienaar** [comment]
I cant seem to find details about their free tier, i see 'try for free' but does that mean it stays free or does it mean its a trial?

**Comment by akar1nchan** [comment]
Free for open source and paid for private use.

**Comment by ripienaar** [comment]
I need to be able to see this mentioned clearly on the site before I can add it, do you have a specific link?

**Comment by yiliangt5** [comment]
@ripienaar @akar1nchan 
Hi both,
I am able to find the pricing terms of GitCafe.com but it seems that this info is in Chinese only: https://help.gitcafe.com/manuals/charge-strategy/content

Following is translated by Google:
All pay fees to use GitCoin
Each private project cost is 4 GitCoin / day
Each time you add a private project collaboration personnel costs 4 GitCoin / day
**Get a free 512 MB per account hosting space**, after the excess of the free use of space, the cost of the excess is 4 GitCoin / 512 MB
30 GitCoin values 1CNY

That's to say each user has 512 MB quota for hosting their public repos for free.

Hope that will help.

**Comment by ripienaar** [comment]
OK thanks.  I am afraid then I can't add this one.  It's not that I don't believe you but I have to be able to easily verify what it says, in the past several chinese and russian sites were submitted and I then too only accepted ones with english pages.

There seems to be a lot of chinese resources that would fit the bill and no doubt a separate list could be made but for this one i'll have to stick with things I can verify and broadly usable which unfortunately means being in English

**Pull request closed without merging**
