### PR TITLE
Rewriting description and removed low quality listing

### PR DESCRIPTION
**Pull request by sriganesh**
## Requirements

 * [ ] This is Software as a Service not self hosted
 * [ ] It has a free tier not just a free trial
 * [ ] Pricing information is clearly visible without signup or phone calls
 * [ ] The submission mentions what is free
 * [ ] The submission is not already present in the list
 * [ ] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by jnadaud** [comment]
👍🏻

**Comment by ripienaar** [comment]
Useful to know why you think that one is a low quality listing.

**Comment by sriganesh** [comment]
The link just promotes booking expert sessions, upgrades, and tipping, lacking substantial free content compared to other listed resources. It appears to have been sneaked in with other high-quality content as part of this [PR](https://github.com/ripienaar/free-for-dev/pull/3120/files). It could potentially be included later when the quality of their content increases.

**Comment by ripienaar** [comment]
Thank you

**Pull request merged**
