### PR TITLE
Add vadoo.tv, video hosting and marketing tool

### PR DESCRIPTION
**Pull request by Anil-matcha**
Free tier for vadoo.tv https://www.vadoo.tv/pricing allows unlimited videos and 10 GB bandwidth/month

### CODE REVIEW

**Comment by iamganeshagrawal** [comment]
Free Tier only allows:

- **Videos/Audios:** 10
- **Storage:** 1GB
- **Bandwidth:** 10GB/mo

**Comment by ripienaar** [comment]
As mentioned by @iamganeshagrawal this description is wrong

**Comment by Anil-matcha** [comment]
@ripienaar Fixed the description now

**Comment by iamganeshagrawal** [comment]
> @ripienaar Fixed the description now

Bro storage is not monthly based

**Comment by Anil-matcha** [comment]
> > @ripienaar Fixed the description now
> 
> Bro storage is not monthly based

Storage per month means how much is the maximum you can keep per month, it is same like bandwidth per month. But if you found it confusing, I have reworded it

**Comment by ripienaar** [comment]
thanks

**Pull request merged**
