### PR TITLE
Stamen Maps is a Free Tile Host

### PR DESCRIPTION
**Pull request by DoreenMichele**
http://maps.stamen.com/#watercolor/12/37.7706/-122.3782

Additional info concerning why I am suggesting it here: https://news.ycombinator.com/item?id=26245538

### CODE REVIEW

**Comment by ripienaar** [comment]
please rebase against latest master, this includes many many comits

**Comment by ripienaar** [comment]
Did you click on the README file then edit or how did you create this one?

**Comment by ripienaar** [comment]
Easiest to open the README in github and hit edit.

Screenshot 2021-03-31 at 11 31 42

**Comment by thispsj** [comment]
@DoreenMichele you've opened a PR for [revert-853-master](https://github.com/ripienaar/free-for-dev/tree/revert-853-master) branch which is not the main branch. Close this one & open a new one. Follow the steps in the link below.

[How to open a PR ?](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

**Comment by DoreenMichele** [comment]
Closing pull request. Will try to open it on the master.

**Comment by thispsj** [comment]
> Closing pull request. Will try to open it on the master.

@DoreenMichele 
👍  If you face any problem, be sure to leave a comment here (if possible with a screenshot).

**Pull request closed without merging**
