### PR TITLE
Update README.MD

### PR DESCRIPTION
**Pull request by elucidsoft**
Added cloudlayer.io to misc

### New Submission Check List

Please ensure your submission ticks all of these boxes:

 - [ ] This is Software as a Service not self hosted
 - [ ] It has a free tier not just a free trial
 - [ ] The submission mentions what is free
 - [ ] The submission is not already present in the list
 - [ ] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by FatGrizzly** [comment]
Seems to be a free trial with only 30 API credits.

>  It has a free tier not just a free trial

Next time, please check the submission checklist and readme.md

**Comment by elucidsoft** [comment]
Ok, that's fine but my competitor on line 1369 would also not meet the criteria.

**Comment by elucidsoft** [comment]
It actually is a free tier that never expires. The verbiage on our site should be changed to reflect that in retrospect.

**Comment by elucidsoft** [comment]
> I dont see any `1369` listed here, can you give us the url
> 
> I know you deleted the comment but you seem to be aware of a incorrect listing so I am curious, anyone is welcome to update the list should they feel it's incorrect. We dont care who competes with who.
> 
> Feel free to re-open later when the free tier has been clarified.

I'm working on updating my pricing for clarity and changing verbiage to remove trial. I'll resubmit my entry when done. Was already in process of doing this in any case.

**Comment by FatGrizzly** [comment]
> I dont see any `1369` listed here, can you give us the url

He refers to the line i suppose, which has a listing to this service(https://uigarage.net/)

**Comment by elucidsoft** [comment]
> > I dont see any `1369` listed here, can you give us the url
> 
> He refers to the line i suppose, which has a listing to this service(https://uigarage.net/)

That wasn't it but I didn't feel comfortable with that comment. Sorry, I made it in haste.

**Pull request closed without merging**
