### PR TITLE
Added jsonbin.io

### PR DESCRIPTION
**Pull request by fiorins**
add jsonbin.io

## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
Maybe it’s because I am on mobile but I can’t see any details of what is free on their site.

**Comment by fiorins** [comment]
These are its plans:

Screenshot 2023-03-16 at 8 59 51 AM

**Comment by ripienaar** [comment]
So you get 10000 requests free and that’s the end of the free plan? That’s how it reads to me in the FAQ. 

That won’t qualify for the list. That’s basically a free trial.

**Comment by handgun50** [comment]
actually jsonbin already removed on #2559 because it only gives 10.000 request only

**Pull request closed without merging**
