### PR TITLE
Add lgtm.com

### PR DESCRIPTION
**Pull request by weyusi**

### CODE REVIEW

**Comment by ripienaar** [comment]
Nice one

**Comment by kfedora** [comment]
I think we can remove LGTM now

lgtm.com redirects to https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/ 

> August 15, 2022 

> Today, GitHub code scanning has all of LGTM.com’s key features—and more! The time has therefore come to announce the plan for the gradual deprecation of LGTM.com.

> 16th of December (of 2022): LGTM.com will be shut down

**Comment by ripienaar** [comment]
You can send a PR to remove it thanks!

**Comment by kfedora** [comment]
> You can send a PR to remove it thanks!

I created a new pull request #2997 to remove it.

**Pull request merged**
