### PR TITLE
End of Service for pullreview.com

### PR DESCRIPTION
**Pull request by kotp**

### CODE REVIEW

**Comment by ripienaar** [comment]
Best to just delete it :)

**Comment by ronal2do** [comment]
screen shot 2018-03-14 at 22 31 14

**Comment by morpheuskafka** [comment]
https://pullrequest.com is alive and well - the screenshot is for https://pullreview.com which is an entirely unaffiliated site

**Comment by ripienaar** [comment]
It’s only the PR title that’s wrong. The entry being removed IS shutting down.

**Comment by ripienaar** [comment]
thank you

**Pull request merged**
