### PR TITLE
Added versioneye under monitoring

### PR DESCRIPTION
**Pull request by thomasbabuj**
Monitor source code and notify about outdated dependencies.

### CODE REVIEW

**Comment by ripienaar** [comment]
monitoring is more for like monitoring the health of a server - maybe this will be more at home under code quality ?

**Comment by thomasbabuj** [comment]
Sue. will update shortly.

**Comment by ripienaar** [comment]
thanks :)

**Comment by thomasbabuj** [comment]
thanks for accepting the PR :)

**Pull request merged**
