### PR TITLE
Add ip-api

### PR DESCRIPTION
**Pull request by bitsnaps**
Add https://ip-api.com a free Geolocation API with 45 req/minute, no API key required.

### CODE REVIEW

**Comment by ripienaar** [comment]
```
curl: (7) Failed to connect to ip-api.com port 80: Connection refused
curl: (7) Failed to connect to ip-api.com port 443: Connection refused
```

sorry this is broken

**Comment by vladc** [comment]
> 
> 
> ```
> curl: (7) Failed to connect to ip-api.com port 80: Connection refused
> curl: (7) Failed to connect to ip-api.com port 443: Connection refused
> ```
> 
> sorry this is broken

Check your hosts/DNS, it's possible you've blacklisted the domain.

**Comment by ripienaar** [comment]
doh, thanks.

**Comment by bitsnaps** [comment]
my bad! I had to explain & curl first, I found it works in a Yii's open source extension:
`curl http://ip-api.com/json/IP_ADDRESS`
docs: https://ip-api.com/docs

**Pull request merged**
