### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ripienaar**
from pr https://github.com/ripienaar/free-for-dev/pull/528

### CODE REVIEW

**Comment by ripienaar** [comment]
@TraderStf this looks good? I had to fix 4 urls in the contents section

**Comment by TraderStf** [comment]
seemzzzokk

**Comment by ripienaar** [comment]
nice, thank you

**Comment by TraderStf** [comment]
I launch a linkssss check

**Comment by TraderStf** [comment]
No bad links.
Just ~150 redirects:
A. http -> httpS
B. ://abc.com -> ://www.abc.com
C. A+B
D. totally new domain
E. subdomain, e.g. abc.com/here -> here.abc.com

I fix D and E now, for the others I need to make a small app.

**Comment by ripienaar** [comment]
Did you see we now have automatic travis check that also does a link check?

**Comment by TraderStf** [comment]
Nope... there is no error, just redirects.
Why also that travis error... see my last PR

**Pull request merged**
