### PR TITLE
add new colaborator

### PR DESCRIPTION
**Pull request by billxcode**
i wanna add some free hosting service and colaborator service

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks for these updates, before I look at them please fix the commit so its not showing all these past commits

**Comment by billxcode** [comment]
iam sorry @ripienaar , ive got littlebit confuse. but now i think , iam on the right way. please check on my new pull request, if its right, i'll close this pull request.

**Comment by ripienaar** [comment]
It's also showing all those commits. Think you need to debase your branch to latest master from this repo

**Comment by billxcode** [comment]
iam done with rebase, hope it right.

**Comment by ripienaar** [comment]
You can tell for yourself - if under "commits" it's shows a bunch of stuff in your PR hat you didn't make then it's still wrong :)

**Comment by ripienaar** [comment]
closing this, unfortunately its still not ok, best to make new PRs forked from `master`

**Pull request closed without merging**
