### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MicheleTiledesk**
## Requirements

 * [ ] This is Software as a Service not self hosted
 * [ ] It has a free tier not just a free trial
 * [ ] The submission mentions what is free
 * [ ] The submission is not already present in the list
 * [ ] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by MicheleTiledesk** [comment]
Added Tiledesk in Miscellaneous

**Comment by MicheleTiledesk** [comment]
sorry, I unintentionally closed the pull request

**Comment by ripienaar** [comment]
Thanks

**Comment by MicheleTiledesk** [comment]
you're welcome!

**Comment by FatGrizzly** [comment]
@MicheleTiledesk just went through your site, Looks really good while being a free one!

Might signup! Thanks!

**Pull request merged**
