### PR TITLE
Postmark Price changes

### PR DESCRIPTION
**Pull request by kevin51jiang**
No longer 25 000 emails free, just a dev account for 100 free/month.

https://postmarkapp.com/pricing

### CODE REVIEW

**Comment by ripienaar** [comment]
for a 100 emails I think we should just remove them from the list, cos whats the point of that.

Want to kill it?

**Comment by beesofts** [comment]
yes it can be simply removed

**Comment by kevin51jiang** [comment]
Postmark Removed

**Comment by ripienaar** [comment]
thank you

**Pull request merged**
