### PR TITLE
Added 'OverOps' to 'Monitoring' category

### PR DESCRIPTION
**Pull request by HennTakipi**
Added OverOps under the monitoring category; short description about the company and their free offering

### CODE REVIEW

**Comment by ripienaar** [comment]
hmm, I merged this one too quick sorry - can you point me at information about the free tier? All I see is about a trial and its not clear how long that is for

**Comment by HennTakipi** [comment]
Hey!

Yeah, we don't have a detailed explanation of what you get for free on the
site, I contacted our team to adjust that.
However, once you sign up for a free trial you can set up the environment
yourself without entering a credit card or talk to anyone from the company.

**Comment by ripienaar** [comment]
Ok I will revert the merge till it’s clear. 

We can only add what we can verify without signing up for 100s of services to discover if they are what they say they are

**Comment by HennTakipi** [comment]
Sure, thanks for the input!

**Pull request merged**
