### PR TITLE
Add Doprax PaaS platform

### PR DESCRIPTION
**Pull request by Misaka-blog**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by FatGrizzly** [comment]
hi, thanks!

can you add the free pricing in this description? it would be more ideal

**Comment by Misaka-blog** [comment]
> hi, thanks!
> 
> can you add the free pricing in this description? it would be more ideal

https://www.doprax.com/pricing/

**Comment by FatGrizzly** [comment]
> > hi, thanks!
> > can you add the free pricing in this description? it would be more ideal
> 
> https://www.doprax.com/pricing/

i mean in the readme.md file, something like 1gb ram and 1 core cpu for only one app is free will do

**Comment by FatGrizzly** [comment]
did it myself, thanks

**Pull request merged**
