### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TraderStf**
http://boundary.com
http://www.bmc.com/truesightpulse/

http://ddos-protection.io
http://athenalayer.com/

http://diffd.com
http://www.instadiff.com/

http://probeapi.com
http://probeapi.speedchecker.xyz

http://vipaar.com
https://www.helplightning.com

https://activestate.com/stackato
http://www8.hp.com/us/en/cloud/helion-overview.html

https://duosecurity.com
https://duo.com

https://nsone.net
https://ns1.com

Set all googles as subdomains

What do you think for this huuuge link type?
http://www8.hp.com/us/en/cloud/helion-overview.html

hp.com Helion
or 
Helion by hp.com (I like this type)
or
Helion

### CODE REVIEW

**Comment by TraderStf** [comment]
what's that TRAVIS...... bug

**Comment by ripienaar** [comment]
Nah just different servers some in reachable. Different ssl trust stores from different machines etc. Quite annoying but it's ok. Better thank nothing :)

**Comment by ripienaar** [comment]
Well now travis won't show me the log. Am on my phone will check later

**Comment by TraderStf** [comment]
OK FORGET ABOUT THIS ONE

SEE README 3

All above and all rewrites are included

**Pull request closed without merging**
