### PR TITLE
Added https://bismuth.cloud

### PR DESCRIPTION
**Pull request by iantbutler01**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by iantbutler01** [comment]
Let me know if I can make this more clear, we're a BaaS with an AI agent to help people quickly build on our platform.

**Comment by ripienaar** [comment]
its not clear from the site what hosting features are free, live deployments it says, but how many apps? for how much usage etc?

**Comment by iantbutler01** [comment]
Got it, will clarify that and then comment back, thanks.

**Comment by iantbutler01** [comment]
Okay I've clarified the offering for our free tier (and our pricing tiers in general)

**Comment by ripienaar** [comment]
Thank you

**Pull request merged**
