### PR TITLE
added ProftiBricks to the IaaS section

### PR DESCRIPTION
**Pull request by baldwinSPC**

### CODE REVIEW

**Comment by baldwinSPC** [comment]
@ripienaar Let me know if this is fine. I noticed in another PR you only get alerted on comment.

**Comment by ripienaar** [comment]
The list is for free tiers, do they have a free tier as well somewhere?

**Comment by baldwinSPC** [comment]
Sadly, this is, currently, the only developer tier posted on the site. If
the PR cannot be merged, then I understand and it can be closed.

**Comment by ripienaar** [comment]
OK in that case it's not suitable for the list, thanks for the effort though

**Pull request closed without merging**
