### PR TITLE
Add a DNS Provider

### PR DESCRIPTION
**Pull request by smesgary**
Add ArvanCloud to DNS Providers

### CODE REVIEW

**Comment by ripienaar** [comment]
We could perhaps expand them a bit as here?

Screenshot 2021-04-08 at 20 35 49

**Comment by smesgary** [comment]
Yes, I think we can do it

**Comment by thispsj** [comment]
@smesgary @ripienaar 
The entry is already expanded. I'd already done that in 7ad8371 commit. You can remove that entry from DNS section as we don't need multiple entries for the same site. Yes you can correct my mistake of ~~sites~~ to domains.

**Comment by ripienaar** [comment]
ah fair, i didnt notice its a dupe, well spotted

**Pull request closed without merging**
