### PR TITLE
Filtering out Rebranded(or fake) cPanel Hosts

### PR DESCRIPTION
**Pull request by FatGrizzly**
will attach enough proof soon

### CODE REVIEW

**Comment by FatGrizzly** [comment]
InfinityFree >
image
Fake cPanel 

Pony.icu
Their cPanel login seems to be down atm
image
The IP of the server is 185.27.134.3
Which is again a Fake cPanel server
image

0hi.id
Fake cPanel
image
(The same old hosting, but they have used Cloudflare Workers to hide that around)

@ripienaar That's it, filtered them all, others seems to be legit enough

**Comment by ripienaar** [comment]
thank you much appreciated

**Comment by ifranwahyudi** [comment]
Hello. 0hi.me here.
is the reason for deleting the three domains above only based on fake cpanel, or is there another reason?

we are not a scam or anything. we provide free hosting for everyone who wants to use it. we provide the support users need when they contact us. 0hi.me even uses a business-grade live chatbot to serve my visitors and provide functionality.

@ripienaar if the reason for deletion is only on "Filtering out Rebranded(or fake) cPanel Hosts", you must clearly state that **no rebranded/reseller services should be included in the submission**, so I don't submit my website from the start.
But, if you delete the three domains above for scam reasons, please remember that we are real, and you can try it yourself. I want you to reconsider it, and the final decision rests with you.

Thank you.

**Comment by ripienaar** [comment]
I am removing these since these kinds of host - not all but how am I to know which - are high churn and a lot of effort and often low quality. 

It’s entirely my decision who I add or remove. I cannot list every possible rule or detect every possible case that match any rules or not.

**Comment by ifranwahyudi** [comment]
understandable, have a nice day

**Comment by facebiik** [comment]
K

**Comment by BastelPichi** [comment]
Don't want to start another discussion here, but:
The hosting is provided by [iFastNet](https://ifastnet.com) via [MyOwnFreeHost](https://myownfreehost.net). They are running quite a few big free hosts.

They never claim(ed), and most of these hosts neither that they have real cPanel. They always say vPanel.
Most of these hosts have been running for multiple years, and although vPanel isn't the best, its still quite OK. It doesn't have all cPanel features, but at least it works and has all features you need for basic websites.

Also for the specs, iFastNet powered hosts are quite good compared to other free hosts, and the support often responds within 3 minutes.

**Comment by FatGrizzly** [comment]
Unfortunately, We don't want a such resellers. They are a big mess and they have really strict limits(non generous) and those aren't welcome here.

Thanks.

**Comment by BastelPichi** [comment]
BTW what about [github.dev](https://github.dev) and [vscode.dev](https://vscode.dev)? Useful, but dont seem them on the list

**Comment by ripienaar** [comment]
If something is missing anyone can add to the list by sending a PR.

**Comment by ifranwahyudi** [comment]
i can not believe someone spreads a lot of misinformation about a service provider, in front of the owner of that service :3
but maybe that is how the internet works, i don't know. i want to debunk it but it's not worth the effort.

for everyone who is reading this pull request, please do your own research. just try our service if you want, it's free. all of the domains listed above have a Trustpilot page, so you can leave your review there and post your experience if you want.

thank you~

**Comment by FatGrizzly** [comment]
At this point, I am done with this.

I can clearly see that you're trying to make some money without spending much bucks by utilising Free Reseller Hosting services, but do you how poor and shit they're?
https://www.trustpilot.com/review/www.byethost.com
https://www.trustpilot.com/review/infinityfree.net?stars=1
and check their forum(forum.infinityfree.net) for such topics on how poor their service is and moreover some of their servers run Cloudlinux 6 which is already EOL.
I don't have access to my pc right now, I have some proofs and documents there.

Will post em once I am back from vacations.

**Comment by FatGrizzly** [comment]
moreover, I was able to get some from the community discord server (The ones with green names are contributiors)

Screenshot_2022-06-02-07-38-00-333_com discord
Screenshot_2022-06-02-07-36-11-727_com discord
Screenshot_2022-06-02-07-27-10-391_com discord
Screenshot_2022-06-02-07-26-33-071_com discord
Screenshot_2022-06-02-07-28-54-951_com discord
Screenshot_2022-06-02-07-36-01-692_com discord

**Comment by ripienaar** [comment]
I am in favour of removing this entire class of service and not accepting new ones.

**Comment by DreamOfIce** [comment]
Hey,I spend less than an hour and $0 on creating a free hosting site on `myownfreehost.net` to to tell anyone how easy to create a free hosting company and use advertisement to profit!
You only need a non free domain(even a subdomain) and an email.
My host site: https://host.dreamofice.cn/
Panel site: http://cpanel.host.dreamofice.com/

The advertisement of the site is free-for.dev😎

**Comment by FatGrizzly** [comment]
See? This is why I hate iFastnet resellers, people wanna make money but doesn't wanna spend a single buck. Thanks for letting everyone here know that ifastnet resellers just come here for advertisements.

Jesus Christ, they don't even force SSL's on login pages.
http://cpanel.host.dreamofice.com/

Super shady company.

**Comment by FatGrizzly** [comment]
I'm going to signup for each free webhosting currently in the list and test it out this weekend.

**Comment by DreamOfIce** [comment]
> I'm going to signup for each free webhosting currently in the list and test it out this weekend.
 
You can also signup my hosting site and compare with other host to show how easy and free to create a free hosting site and get money from advertisement.

**Pull request merged**
