### PR TITLE
Added PageCDN to CDN and Protection Services

### PR DESCRIPTION
**Pull request by praisedpk**
* [PageCDN.com](https://pagecdn.com/) - Offers Public CDN, Private CDN, Shared CDN and Snippets CDN. Public CDN and snippets CDN are totally free. Public CDN includes 100s of opensource libraries, 2000+ WordPress themes, HTML5 themes, Google Fonts, and more.

### CODE REVIEW

**Comment by ripienaar** [comment]
Appears to me this one just hosts open source libraries and even with a free plan you can not actually upload any new content? Or can you upload new content thats public?

**Comment by praisedpk** [comment]
Yes there is. Do you need more detailed information on free and paid offerings?

**Comment by ripienaar** [comment]
We need to be able to easily verify the features of the free tier to be able to add it here basically

**Comment by praisedpk** [comment]
**_We have free offers for all account levels and users_**. PageCDN combines Opensource and Commercial CDN on a single platform. Here is what is free for different types of users:

#### Without Account
- Opensource CDN (like many others on your list including CDNJS, Bootstrap CDN, etc). [Verify here](https://pagecdn.com/lib).
- WordPress themes and plugins. [Verify here](https://pagecdn.com/theme).
- WordPress plugin. Uses API to optimize almost the entire layout of 2000+ WordPress themes for free. [Details](https://wordpress.org/plugins/pagecdn/).

#### With Free Account
Everything above, plus:
- Public CDN API.
- Snippets CDN. (I can send you login info to your twitter for verification of these 2 features).

#### With Paid Plan
Everything above, plus:
- First month free.
- Lifetime free for Opensource or Non-Profit websites. [Details](https://pagecdn.com/about/non-profits).
- Private CDN.

For the Paid subscribers, we still do not charge for the bandwidth they consume from the Public CDN (libs + wordpress themes).

**Comment by ripienaar** [comment]
Ok. Pls trim the description a bit and mention it’s free for opensource / non profit and we are good to merge. Thanks

**Comment by praisedpk** [comment]
Done. Updated description. Thanks for reviewing.

**Pull request merged**
