### PR TITLE
Updated travis.yml

### PR DESCRIPTION
**Pull request by C0derLint**
## Changes
 - Travis now always succeeds irrelevant of the number of dead links.
 - Only shows relevant output.

### Do we need Travis CI?
Well, why not? This will be useful in maintaining the number of dead projects/dead links and can be removed as time passes. Example Travis CI build [here](https://travis-ci.com/C0derLint/free-for-dev/builds/101343148).

### CODE REVIEW

**Comment by ripienaar** [comment]
I removed this on purpose since in practise it just didnt work out at all, temporary failures etc just caused a near constant churn and PR rejections and pain for users.

**Comment by C0derLint** [comment]
I saw your previous comments on that, so I modified this one to build successfully irrespective of result. It's just useful to see number of dead links in the travis ci log.

**Comment by C0derLint** [comment]
what do you say @ripienaar ?

**Comment by ripienaar** [comment]
thanks, lets see how it goes

**Comment by C0derLint** [comment]
Hey @dkhamsing any chance you could add a `--hide-urls` flag?

**Comment by dkhamsing** [comment]
What would this flag do ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by C0derLint** [comment]
It would hide the parsed urls from the output. At the moment, the output is simply piped to grep 

    awesome_bot README.md --allow-dupe --allow-ssl --allow-redirect | grep -Ev "\s*?[0-9]{1,4}\.\s*?http"`

to hide them (see [this](https://travis-ci.com/ripienaar/free-for-dev/builds/101661450) build).

**Pull request merged**
