### PR TITLE
Add porkbun

### PR DESCRIPTION
**Pull request by Tritri1029**
(sometimes porkbun changes its free domains)

### CODE REVIEW

**Comment by Tritri1029** [comment]
excuse me but only .app and .dev are free (https://porkbun.com/event/freeappdevdomain?coupon=TESTANDCODE&utm_source=testandcode&utm_medium=podcast&utm_campaign=tncapril2023) do you want me to do a pull request again?

**Comment by ripienaar** [comment]
Right I see, I cant really list short lasting events here, we need to consider how to maintain the list and about stale information.  This seems a bit adhoc, it's useful for sure, but for us too hard to maintain on this list.

**Comment by Tritri1029** [comment]
Ok thx ;)

**Comment by ripienaar** [comment]
Thank you for contributing

**Pull request closed without merging**
