### PR TITLE
added librato, alphabetized monitoring section

### PR DESCRIPTION
**Pull request by dmangot**

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks, will soon make a better site from data rather than horrid big file :)

**Comment by ripienaar** [comment]
damn, commented on this and somehow my click to merge didnt go through, probably the DoS thing :( do you mind rebasing this? so sorry.

**Comment by dmangot** [comment]
Ok, should be good to go now.

**Comment by leodoni33** [comment]
leodoni33@gmail.com

**Comment by dmangot** [comment]
R.I. I guess it's a little disappointing that I submitted a pull request twice and took the extra time to try and fix the section up for everyone, not just my addition, only to have the PR ignored.

Looks like we're back in merge conflict again.

**Comment by ripienaar** [comment]
Hey Dave,

I am sorry about this one, it's not that I was ignoring it.  I felt bad about asking you to rebase all the time.  At the time of this PR the repo was getting like 20ish - even 32 one day - PRs a day and because yours touch such a lot of lines in the file there was no way it would work.  I ask you to update it, but the time I get to your new PR some other commit touched that part of the file and it wouldn't merge again.

I felt its my fault I shouldn't have made the thing one huge README and felt bad about asking you to redo your hard work each time knowing it's probably cos I missjudged the amount of traffic the repo would get and not doing something that would scale better, at the same time I was moving house and didnt have time to improve things so that a PR like this would get merged :(

Sorry you felt ignored, really wasn't the case just wasn't sure how to get this PR in without literally hitting pause on all PRs between asking you to rebase and getting a update from you again.  But that then would have killed probably ```n``` other PRs as all of them were touching the same section.  Rock and a hard place.

**Pull request closed without merging**
