### PR TITLE
Add GitGud & JSON IP

### PR DESCRIPTION
**Pull request by thispsj**
2 free services added.

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks

**Comment by thispsj** [comment]
@ripienaar if you won't mind can you make me a collab in this repo ? I'm usually searching for such free services so will add here when I find new.
Nvm if you don't wanna add. Just an idea.

**Comment by ripienaar** [comment]
> @ripienaar if you won't mind can you make me a collab in this repo ? I'm usually searching for such free services so will add here when I find new.
> Nvm if you don't wanna add. Just an idea.
> Also I'll help manage the repo and respond to others PRs.

Anyone can send PRs as you've just done, wasn't that a collab?

**Comment by thispsj** [comment]
Ok np fine.
I just wanted to ease out the work.
Nvm I'll continue sending PRs as and when I find new free services

**Pull request merged**
