### PR TITLE
Update README.md with EdgeOne Pages

### PR DESCRIPTION
**Pull request by ringcrl**
This PR has misunderstood: https://github.com/ripienaar/free-for-dev/pull/3521
EdgeOne Pages is a product based on EdgeOne's global acceleration service, and the usage process of EdgeOne Pages itself does not involve any fees and will always provide a free version in the future. Please revert this commit.

## Requirements

 * [ x ] This is Software as a Service not self hosted
 * [ x ] It has a free tier not just a free trial
 * [ x ] Pricing information is clearly visible without signup or phone calls
 * [ x ] The submission mentions what is free
 * [ x ] The submission is not already present in the list
 * [ x ] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
Please screenshot where it says that @ringcrl ?

**Comment by ringcrl** [comment]
image

All capabilities of EdgeOne Pages are under this tab, with no trial time limit, and all webpage deployment features are completely free.

The EdgeOne Pages product homepage is this: https://edgeone.ai/products/pages

**Comment by ripienaar** [comment]
I mean an image that supports what you are saying about it being 100% free and will always be provided for free?

**Comment by axww** [comment]
@ripienaar I've register EdgeOne and tried, confirmed @ringcrl is right, it has a Free Plan.

There's a FAQ on https://edgeone.ai/products/pages
```
Is there a free plan available?
Yes, we offer a free plan that provides unrestricted access to all essential features, ensuring stability and availability for your web applications. This basic free version will always be available, allowing you to build and deploy your projects without any interruptions. As your needs evolve, we will gradually introduce premium features and value-added services to enhance your experience.
```
I'm really sorry made the mistake.
The "Free Trial" under "Get Started" and "14-Day Trial" on Pricing page misleaded me.
It seems like a new product of Tencent Cloud, does not included in Plans page: https://edgeone.ai/document/55650
The "14-Day Trail" is for other modules (CDN etc..), EdgeOne Pages is an individual module.

A suggestion to EdgeOne Pages staffs:
replace "Free Trial, No Credit Card Required!" to "Free, No Credit Card Required!"
Improve Pages pricing model, like storage / traffic limiation included in free plan.

To @ringcrl , thank you for your correct.
However it seems EdgeOne Pages is a simple static pages hosting, like GitHub Pages.
It is better to change your description from:
`EdgeOne Pages enables you to create and launch stunning websites quickly, leveraging edge technology for optimal performance. Free access to all features.`
To:
`EdgeOne Pages enables you to create and launch static websites quickly, leveraging edge technology for optimal performance.`
"Free access to all features." may also make misunderstanding.
You may consider this, cheers.

**Comment by ripienaar** [comment]
Happy to add it once pricing is clear. As per the rules stated in the PR. 

Feel free to open again later when it’s clear, for now have to close as it’s too hard to maintain the list with unclear pricing rules and misleading web pages. 

Thank you.

**Pull request closed without merging**
