### PR TITLE
Add Bruzu.com

### PR DESCRIPTION
**Pull request by motyar**
Bruzu is an API to generate images on the fly.

### CODE REVIEW

**Comment by sriganesh** [comment]
Is there a free plan for this service?

**Comment by motyar** [comment]
Yes you get 100 free API credit when you signup.
Also API is absolutely FREE with watermark.

**Comment by ripienaar** [comment]
Are those credits one off or monthly? One off would not qualify for the list. See the top of the list.

**Comment by motyar** [comment]
One off!
But api is unlimited FREE with watermark on images.

**Comment by ripienaar** [comment]
OK, in that case update the readme entry with something indicating there's a watermark while free

**Comment by motyar** [comment]
Done check https://github.com/ripienaar/free-for-dev/pull/2270

**Comment by ripienaar** [comment]
thank you

**Pull request closed without merging**
