### PR TITLE
Add Altcha.org Spam Filter to Security and PKI

### PR DESCRIPTION
**Pull request by ovx**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by FatGrizzly** [comment]
can you clarify on what is free here?

i couldn't find any mention of free saas offering in the above link

**Comment by ovx** [comment]
Hi, click the big blue button [Get Free API Key](https://altcha.org/docs/api/api_keys), the limits and conditions are described there.

**Comment by ripienaar** [comment]
Please add sometning like “200 requests per day free per domain”

**Comment by ovx** [comment]
Added free plan info, hope it's okay now.

**Review by FatGrizzly — APPROVED** [review]

**Pull request merged**
