### PR TITLE
Create Developer.ga

### PR DESCRIPTION
**Pull request by iam11thsiddharth**
Free domain name to developers, thedev.Id is no longer maintained

### CODE REVIEW

**Comment by iam11thsiddharth** [comment]
Please add developer.ga instead of thedev.Id

Thanks

**Comment by ripienaar** [comment]
Please edit the README.md and put it in there.

**Comment by FatGrizzly** [comment]
Firstly you are using FREENOM to register the free domain "developer.ga" and give it to people?
https://www.whois.com/whois/developer.ga || https://daniel.is-a.dev/blog/freenom-the-free-domains-website-is-a-scam-3

and thedev.id is still being maintained?
https://github.com/fransallen/thedev.id || Last commit 17 days ago.

**Comment by FatGrizzly** [comment]
Closing this PR since author hasn't responded.

**Pull request closed without merging**
