### PR TITLE
Add One VM (Add OneVM Back)

### PR DESCRIPTION
**Pull request by PlurrYT-Kolama**
## Requirements

 * [X] This is Software as a Service not self hosted
 * [X] It has a free tier not just a free trial
 * [X] Pricing information is clearly visible without signup or phone calls
 * [X] The submission mentions what is free
 * [X] The submission is not already present in the list
 * [X] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by PlurrYT-Kolama** [comment]
OneVM wasnt closed but lost their landing page (as it seems), for now they are using wiki for their information. Privacy Policy can be found at home page of wiki

**Comment by ripienaar** [comment]
Hmm this is IPv6 only? Bit of a high bar to use it I think

**Comment by FatGrizzly** [comment]
#3429

**Comment by PlurrYT-Kolama** [comment]
Yeah its ipv6 only but they have information how to set up nat64 and dns64 to access ipv4

**Comment by PlurrYT-Kolama** [comment]
> #3429

It got deleted later due of landing changed + they plans changed

**Comment by ripienaar** [comment]
I think we will pass. It’s low quality, inconsistent and difficult to use. 

Thanks for the effort but best to keep it off.

**Comment by PlurrYT-Kolama** [comment]
> I think we will pass. It’s low quality, inconsistent and difficult to use.
> 
> Thanks for the effort but best to keep it off.

Well, anyways thanks for response. Still wondering what you mean by low quality, using it for decades and it works /shrug\

**Comment by FatGrizzly** [comment]
> > I think we will pass. It’s low quality, inconsistent and difficult to use.
> > 
> > Thanks for the effort but best to keep it off.
> 
> Well, anyways thanks for response. Still wondering what you mean by low quality, using it for decades and it works /shrug\

using for decades... Im genuinely curious why you're bluffing so hard.

Hello, PlurrYT here.
We actually state that we offer 1gb ram 1vcore 15gb storage and 20coins (20 hours) each 24h

You run the service dude?!?

**Comment by PlurrYT-Kolama** [comment]
> > > I think we will pass. It’s low quality, inconsistent and difficult to use.
> > > Thanks for the effort but best to keep it off.
> > 
> > 
> > Well, anyways thanks for response. Still wondering what you mean by low quality, using it for decades and it works /shrug\
> 
> using for decades... Im genuinely curious why you're bluffing so hard.
> 
> Hello, PlurrYT here. We actually state that we offer 1gb ram 1vcore 15gb storage and 20coins (20 hours) each 24h
> 
> You run the service dude?!?

Depends what you mean by run, this account was used before by other person now by other. This was corporative account back then.

**Pull request closed without merging**
