### PR TITLE
1st change branch2

### PR DESCRIPTION
**Pull request by benzlokzik**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
@benzlokzik are you following some guide or training that is instructing you to open these PRs here? We get a lot of them and I want to find out why and try to deal with the problem at the source.

**Comment by umer936** [comment]
@ripienaar I was curious about that too. I watch both this and a similar "awesome" list but this one definitely gets more junk PRs 🤔

**Comment by benzlokzik** [comment]
> @benzlokzik are you following some guide or training that is instructing you to open these PRs here? We get a lot of them and I want to find out why and try to deal with the problem at the source.

My fault, it was misclick, it was an assignment at my university and I chose the wrong branch due to insomnia before class, I apologise again for the inconvenience. I immediately closed the merge request after that when I realised I'd chosen the wrong one 😅

**Comment by ripienaar** [comment]
@benzlokzik does your university mention this repository specifically? We have many people sending this kind of PR and if they do ask people to use this repository it would be great if we can ask them to change their guidance.

There are maybe 1600 people who get notified of PRs here, so I really want the noise to stop :)

**Comment by benzlokzik** [comment]
> does your university mention this repository specifically?

yes, we have a list of variants for each student (depending on the student's number in the list in alphabetical order, there's about 29 similar repos), where each student is given a specific repository to create in fork 2 merge requests and create a merge conflict

**Comment by benzlokzik** [comment]
> There are maybe 1600 people who get notified of PRs here, so I really want the noise to stop :)

I'm not sure that all of them from my university, but I think it is very likely that many universities use this and similar repositories for educational purposes in specialities such as computer science or software development

**Comment by ripienaar** [comment]
Thanks @benzlokzik  It would be great if you could ask your instructors to remove this repo from their lists, its a huge annoyance to 1000s of people if they pick popular repositories to do this against and not fair on the students

**Comment by benzlokzik** [comment]
> does your university mention this repository specifically

I looked at the history of closed pull requests, it's really scary 💀. 

here's a list of recent PRs that are definitely from students from my university
- #3291
- #3290 
- #3284 
- #3264 (not sure)
- #3249 
- #3248 

it scares me. i'm sorry again, it's my fault

**Comment by ripienaar** [comment]
Hehe, no problem, just glad someone finally responds.  I ban these people from the repo which probably mean they cant finish their assignment - and its just annoying all round :)

Hopefully we can get course material updated.

**Comment by benzlokzik** [comment]
> I ban these people from the repo which probably mean they cant finish their assignment - and its just annoying all round

lmao))

> Hopefully we can get course material updated.

i could talk to the lecturer and ask to replace with archived repositories because there are 29 more of them on the list, but I'm not sure he would agree because he is a bit of a grown man with a slightly outdated syllabus (in the tutorials the screenshots of macOS Catalina, google chrome and github are from 2019-2020 I think or older, which means he hasn't updated the material since lockdown), not going out of his way to help the students

**Comment by benzlokzik** [comment]
> I ban these people

btw, please don't ban me, I'm an active user of github and I have ideas what to add here (if i don't find it listed here) 🥹

**Comment by ripienaar** [comment]
haha, so bad, oh well :) thanks anyway @benzlokzik 

Yeah I noticed you were active so figured I'd try to reach you :)

**Comment by benzlokzik** [comment]
> so bad

yeah, stupid and strange programme, because there's a lot students (about 2k or smth like that), some of them don't now what's difference between git and github. so a university programme of study should be suitable for everyone at once

**Comment by umer936** [comment]
Can he not just make a fork of his own that everyone can do the PR to? lol

**Comment by benzlokzik** [comment]
> Can he not just make a fork of his own that everyone can do the PR to? lol

he has his own repos btw, i guess he can use them maybe. i'll talk with him this wed

**Pull request closed without merging**
