### PR TITLE
Add mailbluster

### PR DESCRIPTION
**Pull request by bitsnaps**
mailbluster is an email marketing software with free plan of 62k month and unlimited subscribers.

### CODE REVIEW

**Comment by ripienaar** [comment]
thank you

**Comment by abhay-ranawat** [comment]
Hey it’s now independent, it requires AWS account to send emails , so can it be included here ?
See here _“Yes, MailBluster sends and tracks emails through the user's Amazon account. MailBluster uses Amazon SES for sending and Amazon SNS for tracking emails.”_

**Comment by bitsnaps** [comment]
> Hey it’s now independent, it requires AWS account to send emails , so can it be included here ?
I'm not sure if we can consider the free(mium) AWS account (I'm not using it) which I believe requires a valid visa card.

**Comment by ripienaar** [comment]
Ah you're right, I missed this during review, I'll revert the PR

thank you so much @abhay-ranawat and @bitsnaps

**Pull request merged**
