### PR TITLE
Travis Update 

### PR DESCRIPTION
**Pull request by ReadmeCritic**
This pull request fixes issues with Travis

### CODE REVIEW

**Comment by ripienaar** [comment]
so I am not sure, landscape.io is legitimately throwing a 500, I dont want to forget about it so i left it in - if it keeps throwing a 500 I will just remove it from the list rather than whitelist something that is actually broken.

sounds fair? what do you think?

**Comment by TraderStf** [comment]
it's just their main page... a php bug or htaccess

**Comment by ReadmeCritic** [comment]
Yeah feel free to close and just keep an eye on it :smile:

**Comment by shakna-israel** [comment]
More on the landscape issue [here](https://github.com/landscapeio/landscape-issues/issues/209)

**Pull request closed without merging**
