### PR TITLE
Added RightScale

### PR DESCRIPTION
**Pull request by arangamani**
RightScale is a Cloud Management Platform and offers free trial.

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks

**Comment by TraderStf** [comment]
too bad it is just a 60d trial, that would have been great!

**Comment by ripienaar** [comment]
it seems - their page is crap tbf - that they always give you some amout of free time?

**Comment by ripienaar** [comment]
I dont know, their page sux, so just going to take the cautious route and remove it, sorry

**Pull request merged**
