### PR TITLE
Add image compression tools

### PR DESCRIPTION
**Pull request by barmao**
https://tinypng.com/ : TinyPNG uses smart lossy compression techniques to reduce the file size of your PNG files.

### CODE REVIEW

**Comment by ripienaar** [comment]
Good contribution thanks but this PR is messed up. Thinks it needs a rebase to the current master. Thanks

**Comment by shakna-israel** [comment]
Diffing this pull request against the current master doesn't show any changes for me: https://www.diffchecker.com/bHyEzOSU

I'd guess that what it had proposed has been added since, and it can be merged. @ripienaar ?

**Comment by ripienaar** [comment]
@shakna-israel merging it will hugely confuse the commit history, please rebase

**Comment by shakna-israel** [comment]
*close.

Sorry, wrong word.

It's the same, so we don't need it.

**Comment by ripienaar** [comment]
👍

**Pull request closed without merging**
