### PR TITLE
Added langtrace

### PR DESCRIPTION
**Pull request by Joysbrightt**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
Thanks

**Comment by Joysbrightt** [comment]
Thanks, I'd like to ask when our addition will show up on the website https://free-for.dev/#/?id=generative-ai

**Comment by ripienaar** [comment]
Thanks @Joysbrightt something was wrong with page builds, fixed now

**Comment by Joysbrightt** [comment]
Thanks, appreciate it

**Pull request merged**
