### PR TITLE
Add Lockitbot

### PR DESCRIPTION
**Pull request by Falit**
Lockitbot helps you to reserve and lock shared resources within Slack like Rooms, Servers etc. Free up to 2 resources

## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Review by Wangtt185 — CHANGES_REQUESTED** [review]
1

**Comment by Falit** [comment]
> 1

Hi @Wangtt185 ,  apologies I couldn't understand the comment. Is there a correction which needs to be done?

**Comment by ripienaar** [comment]
Thank you

**Review by Wangtt185 — COMMENTED** [review]
1

**Pull request merged**
