### PR TITLE
Added Deploy Now

### PR DESCRIPTION
**Pull request by hunsalz**
Please add Deploy Now. Thx

### CODE REVIEW

**Comment by ripienaar** [comment]
Screenshot 2021-07-21 at 15 25 47

And what happens after that date? The offer has ended?

**Comment by hunsalz** [comment]
Good point! - I talked to the product owner @Robert95Sch and he promised me that "early access" will be permanently free. Webpage will be updated soon.

**Comment by FatGrizzly** [comment]
nice
image
couldn't imagine a company requiring payment verification for *static hosting*. I just feel like github pages is much better

**Comment by ripienaar** [comment]
@hunsalz ok ping me once web copy is updated

**Comment by Robert95Sch** [comment]
Hi everyone,

the payment verification is a little bit inconvinient, indeed. We need to do this as IONOS customers can purchase more valuable products like servers or domains without additional payment checks. We agree that GitHub Pages is an awesome tool. In contrast to GitHub Pages, Deploy Now does not limit the number of builds and the website's traffic. In addition we offer free features like DDoS protections, geo redundancy, staging deployments, automatic static site generator setups and DigiCert SSL. Our company operates GDPR compliant and our infrastructure is powered by green energy. In addition, we allow customers to build apps using script languages like PHP without charging them. Of course, we constantly want to work on adding more value to the product. The communication regarding the free early access will be updated soon - I'll ping you as soon as it is updated.

**Comment by ripienaar** [comment]
Personally I dont mind the payment verification, honestly its what keep free things free.  We all see the current spasms going through the free CI/CD infrastructure world as bitcoin miners abuse them.

Verification is good, it protects the service and ultimately makes it more likely that the service remains free.

Does it make it better or worse than something else? For the purpose of this list I also do not care.

What I do care about in this kind of setting is if SSL is a feature only available on pay accounts then thats a no go for me (I didnt check this case, just saying as an example).

So let us know when the copy is updated to show this is a long term free plan and I thnk we're ok

**Comment by Robert95Sch** [comment]
Everything I mentioned above is for free, including SSL :-)

**Comment by FatGrizzly** [comment]
> Hi everyone,
> 
> the payment verification is a little bit inconvinient, indeed. We need to do this as IONOS customers can purchase more valuable products like servers or domains without additional payment checks. We agree that GitHub Pages is an awesome tool. In contrast to GitHub Pages, Deploy Now does not limit the number of builds and the website's traffic. In addition we offer free features like DDoS protections, geo redundancy, staging deployments, automatic static site generator setups and DigiCert SSL. Our company operates GDPR compliant and our infrastructure is powered by green energy. In addition, we allow customers to build apps using script languages like PHP without charging them. Of course, we constantly want to work on adding more value to the product. The communication regarding the free early access will be updated soon - I'll ping you as soon as it is updated.

Just read the TOS of ionos, and seems like I am violating if I signup(I'm under 18). So yea. Sad moments

**Comment by thispsj** [comment]
I totally agree with the payment method part.
Even gitlab recently limited their shared runners to payment method verification for new users .

**Comment by FatGrizzly** [comment]
@Robert95Sch Any updates?
3 more days to go

**Comment by Robert95Sch** [comment]
Hi everyone, sorry that this took quite long. The communication on the landing page was updated: https://www.ionos.com/hosting/deploy-now. End dates are removed, all CTAs are generic now. 
Works for you? :-)

**Comment by ripienaar** [comment]
Seems better to me, what do you think @FatGrizzly

**Comment by FatGrizzly** [comment]
> Seems better to me, what do you think @FatGrizzly

Looks good to me too.

**Comment by ripienaar** [comment]
thanks @Robert95Sch

**Pull request merged**
