### PR TITLE
chore: add zitadel cloud

### PR DESCRIPTION
**Pull request by fforootd**
### New Submission Check List

Please ensure your submission ticks all of these boxes:

 - [x] This is Software as a Service not self hosted
 - [x] It has a free tier not just a free trial
 - [x] The submission mentions what is free
 - [x] The submission is not already present in the list
 - [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by eliobischof** [comment]
Would it make sense to create a separate section for IAM solutions?

**Comment by fforootd** [comment]
> Would it make sense to create a separate section for IAM solutions?

If you ask me, yes 😁

**Comment by ripienaar** [comment]
> Would it make sense to create a separate section for IAM solutions?

Yeah would make sense if we have enough entries to move there

**Comment by fforootd** [comment]
If you want I can try and make this. It feels like at least 10 entries are there already.

**Comment by ripienaar** [comment]
That would be great thank you

**Comment by fforootd** [comment]
@ripienaar here you go, hope you like it 😁

**Review by FatGrizzly — APPROVED** [review]
thanks

**Pull request merged**
