### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by unknownhad**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by unknownhad** [comment]
Will appreciate if you can provide a reason of closing it.

**Comment by ripienaar** [comment]
It's pretty clear by visiting https://cloudintel.himanshuanand.com/ why I would not add it to the list.

**Comment by unknownhad** [comment]
Sure, may be sharing that was not the smart move, I have to put API behind auth as bots were hammering it hard.
The other way to consume it is to pull it using Github : https://github.com/unknownhad/AWSAttacks
Hope this clear things up.

**Comment by ripienaar** [comment]
Sorry this is for services, once you have done a bit more work and made a service offering I'd gladly add it.  I can not figure out from your markdown what is going on - its not even valid markdown.

**Comment by unknownhad** [comment]
Sure, I will fix this.
I just put a text response is someone hit without auth. 
Thanks for your response, appreciate it.

**Comment by unknownhad** [comment]
Should I open a new PR or you can reopen this one?

**Comment by ripienaar** [comment]
Either way, new is probably better

**Pull request closed without merging**
