### PR TITLE
Add zdoo.co and zentao.jp

### PR DESCRIPTION
**Pull request by PixelTroy**
Notice:
To open a free site on zentao.jp, you should click クラウド and register an account. And then click 申込み on https://zentao.jp/page/price.html, and choose the "Mini" version. It's completely free forever with limited users and space.

### CODE REVIEW

**Comment by ripienaar** [comment]
Thank you, is there a english version of this page? We can only accept english submissions I am afraid

**Comment by PixelTroy** [comment]
Then i guess zentao.jp is not qualified, but I guess zdoo.co is ok.

**Comment by ripienaar** [comment]
Yes, please update the PR, thank you

**Comment by PixelTroy** [comment]
I have removed zentao.jp, sorry for the delay.

**Pull request merged**
