### PR TITLE
Add awesome list badge

### PR DESCRIPTION
**Pull request by CraigyDavi**
https://github.com/sindresorhus/awesome/issues/253

### CODE REVIEW

**Comment by ripienaar** [comment]
not sure why I would promote this viral badge at the top of the page tbh, why?

**Comment by CraigyDavi** [comment]
> not sure why I would promote this viral badge at the top of the page tbh, why?

Adding this badge creates an easy way for readers of this awesome list to discover more [awesome lists](https://github.com/sindresorhus/awesome) they may like. Essentially it serves for discovery purposes.

**Comment by ripienaar** [comment]
the 90s called they want their shitty webrings back.  no thanks

**Comment by ripienaar** [comment]
And I got the spammy comments in the original ticket on awesome lists too, the very pushy nature and spammy nature that this is being promoted already tells me no thanks

**Pull request closed without merging**
