### PR TITLE
added getstream.io - a newsfeed and activity stream PaaS

### PR DESCRIPTION
**Pull request by DanielBodnar**

### CODE REVIEW

**Comment by ripienaar** [comment]
nice, thanks

**Comment by DanielBodnar** [comment]
I'm still a little unclear the difference between PaaS and BaaS - do you think this would be better filed under BaaS?

**Comment by ripienaar** [comment]
yeah actually I think so, naming things is hard :P

**Comment by ripienaar** [comment]
PaaS is like Heroku, BaaS is like things you might find listed as plugins for Heroku here https://elements.heroku.com/

roughly, but really it's a wavy line

**Comment by DanielBodnar** [comment]
I'll make that change and submit another pull request

**Pull request merged**
