### PR TITLE
Add LeanBoard

### PR DESCRIPTION
**Pull request by dnlhtz**
Collaborative whiteboard with sticky notes for your GitHub issues (Useful for Example Mapping and other techniques)

### CODE REVIEW

**Comment by ripienaar** [comment]
I do not see any detail about their pricing, what I see is ```Start using LeanBoard today.
The first 250 users get a free account!``` which does not say if this is a long term free thing or what the terms are.

Without it being clear I can't really add them to the list I am afraid

**Comment by ripienaar** [comment]
yeah that would be eligible.  if the site copy could be updated to make that clear we'd be good to go

**Comment by dnlhtz** [comment]
@ripienaar that's great, thanks. Updated the site.

**Comment by ripienaar** [comment]
I am not seeing anything indicting the `will be available through GItHub marketplace with a free unlimited plan for public repositories` part in the site copy, all i can see is still the free for the first few accounts

**Comment by dnlhtz** [comment]
@ripienaar gotcha, thought you just wanted it to be more clear it's *forever* free and *unlimited*. Now added the marketplace info as well.

**Comment by dnlhtz** [comment]
@ripienaar added it on the [homepage](https://www.leanboard.io/)

screenshot 2018-11-25 00 33 08

**Comment by ripienaar** [comment]
Thank you :)

**Comment by dnlhtz** [comment]
Thank you @ripienaar :)

**Pull request merged**
