### PR TITLE
Email: Smtpjs.com

### PR DESCRIPTION
**Pull request by OgbeniHMMD**

### CODE REVIEW

**Comment by ripienaar** [comment]
What is the SaaS service here? Looks like just a JS library.

**Comment by OgbeniHMMD** [comment]
"It is not possible to send emails using SMTP servers with JS or Jquery. SMTPJs gives us API but eventually we are using their servers to hit the SMTP. actually we are sending data to their server which further sends data to SMTP servers.”

Ref: https://stackoverflow.com/questions/46936506/smtpjs-api-not-working-is-there-any-way-to-send-emails-using-smtp-server-with-j

**Comment by ripienaar** [comment]
I am aware how SMTP works. In the scenario if you offered a free SMTP server that would be a SaaS. A JS library, unless a fromtend to a SaaS with a free tier, is not a SaaS

**Comment by OgbeniHMMD** [comment]
Oh! I think I get your point now.

**Comment by ripienaar** [comment]
Thank you

**Pull request closed without merging**
