### PR TITLE
append Trello into the 'Tools fro teams & Collaboration'

### PR DESCRIPTION
**Pull request by FrankBian**

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks

**Comment by wind39** [comment]
Trello was already listed on "Issue tracking / Project management".

**Comment by ripienaar** [comment]
ah thanks, was lazy when i woke up and didnt check :P will revert

**Comment by wind39** [comment]
:+1:

**Comment by FrankBian** [comment]
sorry

**Pull request merged**
