### PR TITLE
Update https://free-for.dev/#/ list and add UXtweak

### PR DESCRIPTION
**Pull request by marzipanina**
[https://www.uxtweak.com/](url) all-in-one UX research platform providing tools for usability testing, information architecture research, and behavior analytics.

### CODE REVIEW

**Comment by thispsj** [comment]
Bruh ... 
@marzipanina this is not the correct way to open a PR (Pull Request)

Refer this for more :

[How to open a PR ?](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)
[How to open a PR from a branch on my fork ?](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
[What is a Fork ?](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks)

**Comment by thispsj** [comment]
@ripienaar what I think is you should delete the branches which are not in use (if it's not important to you) so that people don't get confused.

**Comment by ripienaar** [comment]
Yeah that's a good idea, we'd need to close all PRs referencing them as GH doesnt allow them to be deleted.

**Comment by thispsj** [comment]
Probably start closing PR from here ?

**Comment by ripienaar** [comment]
Sometimes people come back and update their PRs, so I tend to leave htem and every now and then do a bunch of closes on ancient ones

**Comment by thispsj** [comment]
> Sometimes people come back and update their PRs, so I tend to leave htem and every now and then do a bunch of closes on ancient ones

Ya but this PR can't be merged anyways so ?

**Comment by ripienaar** [comment]
PRs can be updated, this PR can easily be fixed by the author for example.

**Comment by thispsj** [comment]
> PRs can be updated, this PR can easily be fixed by the author for example.

Ahh yes but the user is new so I don't think they may update. Well nevermind let's wait.

**Comment by ripienaar** [comment]
closing in order to delete old branches, please re-add on master.  thanks

**Pull request closed without merging**
