### PR TITLE
Various grammar fixes 

### PR DESCRIPTION
**Pull request by peterkos**
Fixed capitalization to be more consistent
Removed an extreneous use of it's
Updated description of AreoFS
Repunctuated introduction

### CODE REVIEW

**Comment by ripienaar** [comment]
ah yikes should have merged this one first before others - so now it wont merge cleanly :( Really sorry, do you mind rebasing?

**Comment by ripienaar** [comment]
But wait a bit, there are a number of PRs more to merge this morning :)

**Comment by peterkos** [comment]
Ok! I'll rebase and merge later tonight

**Comment by ripienaar** [comment]
its no biggie though, I'm just gathering raw data and will make a new website out of this data - so for now it doesnt have to be perfect, I appreciate it though :)

**Comment by peterkos** [comment]
:shaved_ice: Fixed the conflicts, ready to merge at your command

**Comment by ripienaar** [comment]
merged thanks a lot - now no doubt all the other PRs will fail lol

**Pull request merged**
