### PR TITLE
Add Contentful

### PR DESCRIPTION
**Pull request by SaschaKonietzke**
Add Contentful as a Content as a Service provider (CaaS)

### CODE REVIEW

**Comment by ripienaar** [comment]
probably more accurately described as CMS rather than ever more nebulous *aaS, but am not keen to just add more niche catagories so can you pop this one into PaaS?

thanks

**Comment by SaschaKonietzke** [comment]
Sounds good. I've moved it to BaaS now, which seems to fit a lot better than PaaS (more the Heroku kind of platforms). I hope this is ok, let me know if I should change it.

**Comment by ripienaar** [comment]
ah looks like its not a clean merge now, do you mind rebasing?

**Comment by SaschaKonietzke** [comment]
Not the git pro unfortunately... do you mind if I create you a new pull request with only one commit? Or do you have an easy command for me to execute? Thanks and apologies for the back and forth.

**Comment by ripienaar** [comment]
thats fine too, I'll hold off merging things till you do :)

**Pull request closed without merging**
