### PR TITLE
Add Conveyor

### PR DESCRIPTION
**Pull request by keyoti**
Add free Conveyor tool to the list.

### CODE REVIEW

**Comment by ripienaar** [comment]
Am I right in saying the cloud service doesnt have a free tier its only the extension that allow local LAN access thats free and to get internet access you have to buy a license?

If thats the case I dont think its a good fit for this list as the as-a-service side need a free tier.

**Comment by keyoti** [comment]
No, it’s free you just have to signup for an account.  Right now it’s all free beta and in future the tunnel will have a free tier and a paid tier.

 

Thanks for your consideration.

**Comment by ripienaar** [comment]
```You’re signing up for free beta service that will run for a few months, afterwards we may continue to have a free tier.```

As per the top of the readme it needs a long free tier and if in beta a firm commitment for a ongoing free tier after beta. 

I need to be able to verify the free aspect on the website

**Comment by keyoti** [comment]
Thanks, that is reasonable – I have updated the website to clearly state it 

 

https://conveyor.cloud/Account/Register

**Comment by ripienaar** [comment]
thanks

**Pull request merged**
