### PR TITLE
added cloud_dev02

### PR DESCRIPTION
**Pull request by atesham213**
### New Submission Check List

Please ensure your submission ticks all of these boxes:

 - [x] This is Software as a Service not self hosted
 - [x] It has a free tier not just a free trial
 - [x] The submission mentions what is free
 - [x] The submission is not already present in the list

### CODE REVIEW

**Comment by atesham213** [comment]
please approve this request

**Comment by atesham213** [comment]
please approve this request

**Comment by ripienaar** [comment]
@atesham213 please tell me who told you to open PRs here while learning? Is it some guide?

**Comment by rachit1601** [comment]
> please approve this request
This repository is not for testing. Please don't do such things in public repos

**Review by rachit1601 — CHANGES_REQUESTED** [review]
SPAM

**Pull request closed without merging**
