### PR TITLE
sandstorm.io

### PR DESCRIPTION
**Pull request by garrmark**
Sandstorm.io is an open source hosting platform for personal/private instances of web apps. Users can upload and install arbitrary software through a simple app-store-like web interface. In addition to better privacy, this is the only way to make Open Source web apps viable.

### CODE REVIEW

**Comment by ripienaar** [comment]
hard to make out exactly what this is - looks like they have a self hosted option and some option for managed hosting.  But there are no pricing for the managed hosting version to be found.

I've in the past not accepted self hosted software so if the free part is self hosting I dont think it would fit here.

Can you point me at pricing info for the managed hosting part?

**Comment by shakna-israel** [comment]
It's accessible once you sign up... But that's annoying as hell.

The prices listed in the [release announcement](https://blog.sandstorm.io/news/2015-08-31-oasis-beta-launch.html) are still the same as far as I'm aware.

**Comment by ripienaar** [comment]
OK, then as nice as this looks I dont think it really fits the bill for this :( there's no ongoing free tier (during beta only...) and the only free option is self hosted

sorry :(

**Comment by garrmark** [comment]
No worries, I couldn't find pricing either so I thought there was a free option.

**Pull request closed without merging**
