### PR TITLE
Removed quay.io

### PR DESCRIPTION
**Pull request by SangramChavan**
No free tire https://quay.io/plans/
  * [quay.io](https://quay.io/) — Unlimited free public repositories

### CODE REVIEW

**Comment by ripienaar** [comment]
from that page: 

```
Can I use Quay for free?
Yes! We offer unlimited storage and serving of public repositories. We strongly believe in the open source community and will do what we can to help!
```

**Comment by SangramChavan** [comment]
Ohh i missed that !!

**Comment by ripienaar** [comment]
:) yeh easily missed, they often hide these offers! thanks for attempting to improve it though appreciate the effort

**Comment by SangramChavan** [comment]
+1 Next time will be more careful !!

**Pull request closed without merging**
