### PR TITLE
Add TinkerHost

### PR DESCRIPTION
**Pull request by TinkerHost**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by FatGrizzly** [comment]
Please read the code of conduct.

We do not accept    * cPanel like PHP + MySQL hosting services.

**Comment by BastelPichi** [comment]
Maybe it would be helpful to actually add an code of conduct? lol

**Comment by ripienaar** [comment]
@BastelPichi when you opened the PR it had this text in it.

```
### Code of Conduct

 We are not here to argue with you. If you are argumentative, abusive,
 lie or missrepresent your service or are otherwise anti-social we will
 block you.

 ### Services we do not accept

   * cPanel like PHP + MySQL hosting services.
   * Free dns services that are generic frontends to CloudFlare or similar
   * Services that are verbatim copy pastes of others while adding no value
```

**Comment by BastelPichi** [comment]
NVM, was about to come back. GotHub wont show it in the pr template preview...

**Comment by GenerateHost** [comment]
There is a common misconception among some users that VistaPanel hosts are "fake cPanel" hosts. However, this is not an accurate description of VistaPanel hosts and can lead to confusion for users who are not familiar with the differences between the two.

While VistaPanel and cPanel share some similarities in terms of functionality and features, they are fundamentally different platforms with distinct interfaces and design philosophies. VistaPanel is a proprietary web hosting control panel developed by iFastNet, whereas cPanel is a commercial web hosting control panel developed by cPanel, LLC.

One key difference between VistaPanel and cPanel is that VistaPanel is designed specifically for use with MyOwnFreeHost reseller hosting, whereas cPanel is designed to work with a wide variety of hosting platforms. Additionally, VistaPanel offers a streamlined interface and feature set that is tailored to the needs of resellers, whereas cPanel offers a more comprehensive set of features and tools that are suitable for a wider range of hosting scenarios.

Therefore, it is important to clarify that VistaPanel hosts are not "fake cPanel" hosts, but rather a unique and distinct web hosting control panel designed specifically for use with MyOwnFreeHost reseller hosting.

I propose that we update our documentation and marketing materials to reflect this distinction, and to provide users with a clearer understanding of the benefits and features of VistaPanel hosting.

Please feel free to share your thoughts and feedback on this issue, and let's work together to ensure that our users have a clear and accurate understanding of the differences between VistaPanel and cPanel hosting.

**Pull request closed without merging**
