### PR TITLE
add openode

### PR DESCRIPTION
**Pull request by martinlevesque**

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks!

**Comment by maple3142** [comment]
I wonder why this is listed here?
`README.md` said:
```
NOTE: This list is only for as-a-Service offerings, not for self-hosted software. For a service to be eligible it has to offer a Free Tier and not just a free trial. If the Free Tier is time bucketed it has to be at least a year.
```
But I can only find that it provide 30 days free instance for any registered user, no mention to open source projects.
BTW, the [fisrt result on Google](https://www.google.com.tw/search?q=openode+open+source) had been removed, it seems like they cancelled this project.

**Comment by ripienaar** [comment]
often companies update their sites or free offerings, constant struggle.

if its not clear on their site what they offer i am happy to just delete it via a PR

**Comment by ripienaar** [comment]
thanks :)

**Pull request merged**
