### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aleluff**
Add WebDB

## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] Pricing information is clearly visible without signup or phone calls
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
thanks

**Comment by aleluff** [comment]
Thanks to you =)

Can I ask you a favor by giving me feedback on the app and / or website please

Best

**Comment by ripienaar** [comment]
I can't really review each of the 1000+ websites here :) I evaluate if they meet the criteria and thats about it.  Sorry.

**Comment by aleluff** [comment]
No problem, I just terribly need some feedback, even short

**Pull request merged**
