### PR TITLE
Add Nango to the Auth section

### PR DESCRIPTION
**Pull request by rguldener**
## Requirements

 * [x] This is Software as a Service not self hosted
 * [x] It has a free tier not just a free trial
 * [x] The submission mentions what is free
 * [x] The submission is not already present in the list
 * [x] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by rguldener** [comment]
Direct link to the service's website: https://www.nango.dev
Pricing page: https://www.nango.dev/pricing

**Comment by FatGrizzly** [comment]
sounds like a self hosted option only? cloud one seems paid.

**Comment by ripienaar** [comment]
Seems to me cloud includes 10 for free connections then $0.5/month. But if it means like 1 single auth request is a "connection" then lol, no thats just not a free service.

**Comment by ripienaar** [comment]
ahh, `1 A connection is an active OAuth token, where Nango handles the OAuth flow for the end-user, secure token storage and automatic refreshing.` so 10 active oauth tokens a monht, I dont think thats enough to be useful to anyone.

**Pull request closed without merging**
