### PR TITLE
Add Track Awesome List

### PR DESCRIPTION
**Pull request by theowenyoung**
Hi, @ripienaar :

I'm Owen, a big fan of free-for-dev. After discovering this awesome list, I read all kinds of interesting items in the entire list. After that, I wanted to see what updates were made to this list every once in a while, and had to go through Github's commit history to see what was updated for each commit. To be honest, it was quite a poor reading experience.

So for this need, I created [Track Awesome List](https://www.trackawesomelist.com) in my spare time, and created a profile for free-for-dev, https://www.trackawesomelist.com/ripienaar/free-for-dev . With this link, we can read the latest updates of free-for-dev by day/week, free, daily updated. I wonder if anyone else has this need to see the latest updates, and if so, whether to add this link somewhere in the readme to tell others they can see the updates via this link?

I also created a badge for free-for-dev, which can also be linked to the timeline of free-for-dev.

[Track Awesome List](https://www.trackawesomelist.com/ripienaar/free-for-dev)

```bash
[![Track Awesome List](https://www.trackawesomelist.com/badge.svg)](https://www.trackawesomelist.com/ripienaar/free-for-dev)
```

Let me know what you think. I'm happy to receive any feedback or suggestions for improvement. I want this to be as useful as possible.

If you don’t think it’s necessary, that’s okay. I really appreciate you maintaining such an awesome list. I like this list.

### CODE REVIEW

**Comment by ripienaar** [comment]
thats nice, maybe we can move it down below the main title? like just before the `NOTE:....` section seems sensible?

**Comment by theowenyoung** [comment]
that's okay, do you think we should use text and link, or just badge?

**Comment by ripienaar** [comment]
I like the badge

**Comment by ripienaar** [comment]
nice one

**Pull request merged**
