### PR TITLE
Update Travis

### PR DESCRIPTION
**Pull request by dkhamsing**
Using test branch and setting timeout

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hm looks like there's a logic error.. will work on it

**Comment by dkhamsing** [comment]
Updated again, looks better but these issues remain

1. 502 https://ideascale.com/
2. https://debugmail.io/ SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I would recommend white listing them

I will let you know when the changes are released

Thanks

**Comment by ripienaar** [comment]
kewl, well of course some are just dead or broken and should be removed too :) 

thanks for the work on this, do you still need this or can i close it?

**Comment by dkhamsing** [comment]
Yes please leave this 
Will test again after I publish it as a gem

**Comment by dkhamsing** [comment]
Hey @ripienaar awesome_bot now supports `--allow-timeout` and `--set-timeout`, thanks for helping me test. Let me know if it works for you

Will close this

**Comment by ripienaar** [comment]
nice one! thanks a lot for that

**Pull request closed without merging**
