### PR TITLE
Clean all markdown links

### PR DESCRIPTION
**Pull request by TraderStf**
Cleaned with regex to have short link markdown, [name](url)

github seems to have some problem with the link/ref on top... changes are not 'logical'
ok on third party validator, perhaps just the preview?

### CODE REVIEW

**Comment by TraderStf** [comment]
Regex used, not 100% perfect, some sentences were... not ~standard
```
  \* (https?://)(www\.)?([a-z]+\.)?([\da-z_\.-]+)(.+)? - ([a-z\d])
  * [\3\4](\1\3\4\5) — \6
```

**Comment by ripienaar** [comment]
https://github.com/TraderStf/free-for-dev/blob/patch-14/readme2.md is how it will be rendered by github?

**Comment by TraderStf** [comment]
ok with your link, the preview did not 'link/underline' few menus on top.

with few links are in { } brackets ?

**Comment by TraderStf** [comment]
great I can launch a link checker on the one you just put here

**Comment by TraderStf** [comment]
These are picky, must have www. or something different to be ok
I update them

https://www.datadoghq.com
https://www.apicastor.com
https://www.foxpass.com
https://www.cloudamqp.com
https://www.simplybuilt.com
https://www.pythonanywhere.com
https://www.sumologic.com
https://www.opswatgears.com

https://cloud.google.com/container-engine/
https://cloud.google.com/compute/

**Comment by ripienaar** [comment]
they render fine for me?

**Comment by TraderStf** [comment]
yes but not in the preview, copy the code, open a new doc, paste it, go to preview... at least for me... mac safari.....

**Comment by ripienaar** [comment]
oh i see, thats weird, not sure why that is - but sounds like a github bug :)

**Comment by TraderStf** [comment]
Yes, they are display correctly in BBEdit, even with few ~changes - -- etc...

**Comment by TraderStf** [comment]
a problem?

**Comment by ripienaar** [comment]
Sure, there's readme2 I am not sure what the plan with this PR is :)

**Comment by TraderStf** [comment]
you do a copy paste because when I have try to update/PR the readme, there was always errors...???
can't PR... sorry, should have explained to you

**Comment by ripienaar** [comment]
Ah I see, ok let me see :)

**Pull request closed without merging**
