### PR TITLE
Added "Bitbucket Pipelines"

### PR DESCRIPTION
**Pull request by bloep**

### CODE REVIEW

**Comment by JABirchall** [comment]
BitBucket pipelines is a service only avalble if your using bitbucket right? Its not something you can use if your using github for instance.

**Comment by bloep** [comment]
Yes, it's Bitbucket only.

**Comment by ripienaar** [comment]
bitbucket is already listed, I'd rather if there's some significant addition we just updated the existing description

**Comment by ripienaar** [comment]
👍 thank you

**Pull request merged**
