### PR TITLE
Adding MongoLab

### PR DESCRIPTION
**Pull request by caffeinewriter**
MongoLab offers 500mb free for development.

https://mongolab.com/plans/pricing/

### CODE REVIEW

**Comment by ripienaar** [comment]
According to https://github.com/ripienaar/free-for-dev/pull/276 mongolab is removing their free tier, I've asked if the author of that PR has some more info but for now that's why it's not in here already

**Comment by caffeinewriter** [comment]
Thanks for the heads up @ripienaar. I'll see if I can find more info on that.

**Comment by appleboy** [comment]
@caffeinewriter :+1:

**Comment by caffeinewriter** [comment]
@ripienaar Mongolab has confirmed that the free plan is *not* being removed.

https://twitter.com/mongolab/status/596655984359112704

**Comment by ripienaar** [comment]
right, thanks for following up. wtf then :)

**Pull request merged**
