### PR TITLE
Machine Learning

### PR DESCRIPTION
**Pull request by SangramChavan**
Added TensorFlow

### CODE REVIEW

**Comment by ripienaar** [comment]
while this is useful, it does not really fit the purpose of this list sorry.

`This is list of software (SaaS, PaaS, IaaS, etc.) and other offerings that have free tiers for developers.`

So we can't really list every tangentially related open source project, have to limit to `*aaS`, I can't see that this has a hosted component to it?

**Comment by SangramChavan** [comment]
Okay! What's your opinion on Sandstorm.io is an open source operating system for personal and private clouds. Would this fit into the list as PaaS ?

**Comment by ripienaar** [comment]
yes, based on https://sandstorm.io/get#managed-hosting there's a free hosted service, that'd be a good fit

**Comment by SangramChavan** [comment]
Superb @ripienaar this would be my first contribution on GitHub

**Comment by ripienaar** [comment]
amazing, glad to be your first :)

Do you want to make a new PR and close this one or update this one?

**Comment by ripienaar** [comment]
oh, I see you updated - remove tensorflow please :)

**Comment by SangramChavan** [comment]
Removed tensorflow is Sandstorm fine or i need to update the url as you suggested

**Comment by ripienaar** [comment]
URL is fine, maybe just add some details on what is free like in the others? like "200MB storage and 5 grains free" or something

**Comment by SangramChavan** [comment]
Done :)

**Comment by ripienaar** [comment]
awesome, congrats @SangramChavan

**Comment by SangramChavan** [comment]
Thanks a lot :)

**Pull request merged**
