### PR TITLE
changed  ⬆️Back to Top to an icon that links to Table of contents

### PR DESCRIPTION
**Pull request by Yuheshpandian**
I did not add any new services.

## Things I changed:

- I just replace every occurrences of ⬆️ Back To Top ---> An shields.io image/icon that links to the table of contents, so the overall README.md would look nice and relevant to the Theme of the Site.

### CODE REVIEW

**Comment by ripienaar** [comment]
To me its a bit big and overbearing, any smaller options in mind?

**Comment by Yuheshpandian** [comment]
> To me its a bit big and overbearing, any smaller options in mind?

I cant get what you are meaning, are you feeling this PR to be very large to review or you feel that this PR is out of the scope of the repo or useless in nature.

If you want to review this in simple way review it in my forks [README](https://github.com/Yuheshpandian/free-for-dev/blob/master/README.md)...

**Comment by Yuheshpandian** [comment]
ok I will change it according to you guidance ASAP

**Comment by Yuheshpandian** [comment]
Hi @ripienaar I have minimized the size of the asset and added it as an local svg assets in the *assets/* folder. You can even add any further assets in the assets folder. Please review the changes and inform if any changes needed.

Thank You

**Comment by ripienaar** [comment]
Nice, thanks

**Comment by ripienaar** [comment]
Screenshot 2024-02-25 at 15 26 47


Looks to me a bit like this green is too bright - I know it lines up with the github logo but maybe a better choice if it was same as the font color? The white is also not really readable on this, migth be better on font color

**Comment by Yuheshpandian** [comment]
> Screenshot 2024-02-25 at 15 26 47
> Looks to me a bit like this green is too bright - I know it lines up with the github logo but maybe a better choice if it was same as the font color? The white is also not really readable on this, migth be better on font color

If possible by today I will try to make the logo to be in the color of the links and the font color to be in the color of the bodys' background. Is this change will look nice

**Comment by ripienaar** [comment]
@Yuheshpandian Will you have time to fix this? Else I'll go ahead and revert these commits.

**Comment by Yuheshpandian** [comment]
No need to revert I will work only on the svg, is This ok...

**Comment by ripienaar** [comment]
Yes, thank you

**Pull request merged**
