### PR TITLE
add asana for Team Collaboration

### PR DESCRIPTION
**Pull request by aruntakkar**
your list is great we can add asana free team collaboration Also what's your take on this

### CODE REVIEW

**Comment by ripienaar** [comment]
it's good, but unfortunately already on the list

**Comment by aruntakkar** [comment]
But we should put it in the team collaboration Data or not?

**Comment by ripienaar** [comment]
you could move it if you like, but I dont want it listed twice the list will become insane if we did that

**Comment by aruntakkar** [comment]
Good no problem :)

**Pull request closed without merging**
