### PR TITLE
Revert 1 iam11thsiddharth patch 1

### PR DESCRIPTION
**Pull request by iam11thsiddharth**
## Requirements

 * [ ] This is Software as a Service not self hosted
 * [ ] It has a free tier not just a free trial
 * [ ] The submission mentions what is free
 * [ ] The submission is not already present in the list
 * [ ] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by iam11thsiddharth** [comment]
Hi, can you add devlopr.site

**Comment by iam11thsiddharth** [comment]
@ripienaar 
That's https://devlopr.site

**Comment by ripienaar** [comment]
No, as it states in the PR template, we dont accept these kinds of sites.

**Comment by iam11thsiddharth** [comment]
What do u mean by this kind of sites ?

**Comment by iam11thsiddharth** [comment]
Also the homepage is still in development

**Comment by iam11thsiddharth** [comment]
So if u can issue this will be a plus 👍
@ripienaar

**Comment by ripienaar** [comment]
My main concern with these kinds of service is that, in general, they are all terrible and does not add any real value. I have often told these kinds of projects to go away and do something proper and then come back.

This service though is different, there is proper effort made to create a website, a dahsboard, admin screeens and such.

I would therefor add it once its more mature, you are welcome to come back when you're feeling that you're near to ready for prime time and we can take a look @iam11thsiddharth 

thanks

**Comment by iam11thsiddharth** [comment]
Really thanks for your wise words.
But really I am very dedicated for it and I am constantly trying to improve it.
Can you please suggest some area which needs improvement 🙏
A few hours ago I updated the homepage hope you saw that.

**Comment by iam11thsiddharth** [comment]
One more thing I would like to ask you that giving option to create txt record will be harmful choice  ?
Because we are only providing cname record and A record options 
@ripienaar

**Comment by ripienaar** [comment]
As you stated yourself its a work in progress.  

We arent not here to help you with your site deisgn and such. 

I would say though a "sub domain" requires NS records, thats the minimal I'll accept.

**Comment by iam11thsiddharth** [comment]
Oh yes, i got it @ripienaar 
But it's in deployed stage and users are needed and I don't think there's any other platform other than free for dev to Kickstart and get users.
So please consider it

**Comment by ripienaar** [comment]
Plenty of our sources for early feedback. HN, Reddit, etc.

**Comment by ripienaar** [comment]
Like I said. Once your service is mature. 

And you need to support NS records. That’s the minimal requirement for a “subdomain”. 

Please don’t keep nagging.

**Comment by ripienaar** [comment]
Both reddit and HN are better places to get developer feedback. Suggest you go there.

Screenshot 2023-04-19 at 21 59 13
Screenshot 2023-04-19 at 21 59 03

**Comment by iam11thsiddharth** [comment]
Fine, no nag.
But one thing, u sent Y combinator search results but our service is not a startup, just a free service
Next as said earlier I never went to reddit but went to discord.

**Comment by ripienaar** [comment]
Neither is free for dev and it’s mentioned often on both. They are places for general developer discussion and have more eyes than this.

**Comment by iam11thsiddharth** [comment]
Remember once a service is mature it doesn't need any free for dev.
If Free for dev can't help in early days it should not morally include our service once it's mature.

Yes free for dev may have been mentioned in those sites but that doesn't mean it will not include services that are not mentioned there.
Line is thick but have whole big difference 

@ripienaar

**Comment by ripienaar** [comment]
Right so the thousands of services here of very mature companies like AWS and Microsoft?

this list isn’t here to serve businesses it’s here to serve every day developers. If you want to use this as your promotion space and not go or the spirit of the site. Then you aren’t welcome here. 

I said my piece. You come back when you are a mature service ready for prime time or the ban on DNS services stand. The reason for the ban is that I am sick of developers working on DNS services behaving exactly like you are doing now. 

I suggest your next reply is weeks or months from now when you have a mature service.

**Comment by iam11thsiddharth** [comment]
I think u have a misconception that the service is a business, it's a free service to be clear for everyday Dev's.
Who said I want to use it as a promotion ?
I could have easily used ad services to advertise. Because we thought the list has potential and can have a fair usage by developers. That's it

One more thing even if I integrate NS records, be a mature service (I don't know why I m speaking your language) will never come back. It was my mistake, it was clearly my fault because I tried to convince u (which by your replies i shouldn't). U could have told me earlier that u are sick of Dev's working on DNS services 

Anyways 

Forget about our conversation, no issues
But remember If Free for dev can't help in early days it should not morally include service once it's mature.
😃

**Comment by ripienaar** [comment]
I told you DNS seervices are not welcome here, before you even opened the PR.  I thought this one had potential, I was wrong.  Bye.

**Pull request closed without merging**
