### PR TITLE
Re-added HelioHost since free signups are available again

### PR DESCRIPTION
**Pull request by Kryd0s**
Added HelioHost under Web Hosting category.

## Requirements

 * [X] This is Software as a Service not self hosted
 * [X] It has a free tier not just a free trial
 * [X] The submission mentions what is free
 * [X] The submission is not already present in the list
 * [X] The service has contact details of those running it and a privacy policy

### CODE REVIEW

**Comment by ripienaar** [comment]
Nope, not adding it. Had enough spammers and general abuse here from it or people who support it.

**Comment by ABUCKY0** [comment]
@FatGrizzly

**Comment by ABUCKY0** [comment]
> Nope, not adding it. Had enough spammers and general abuse here from it or people who support it.

Can you elaborate on the spammers and general abuse from HelioHost supporters? I was only able to find one other mention of it in the pull requests on an unrelated PR comment.

**Comment by ripienaar** [comment]
Yes, that one. Though I believe some PRs are not visible due to abuse claims maybe?

It also seems severely resource constraint etc.

Anyway, I am not adding it again.

**Comment by Kryd0s** [comment]
One of the other web hosting listings you have only offers 50 MB storage, and HelioHost has 1000 MB storage. I don't understand how that is "severely resource constraint" in comparison.

Also ChippyTech, if that's the spammer you're referring to, has absolutely no affiliation with HelioHost. We have about 5k accounts right now, and we can't be held responsible for the behavior of every single one of them.

**Pull request merged**
